//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class ConfigSistema1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigSistema1 defaultInstance = ((ConfigSistema1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigSistema1())));
        
        public static ConfigSistema1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UrlBd {
            get {
                return ((string)(this["UrlBd"]));
            }
            set {
                this["UrlBd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathImage {
            get {
                return ((string)(this["PathImage"]));
            }
            set {
                this["PathImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathInstall {
            get {
                return ((string)(this["PathInstall"]));
            }
            set {
                this["PathInstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorExitTxtBox {
            get {
                return ((global::System.Drawing.Color)(this["ColorExitTxtBox"]));
            }
            set {
                this["ColorExitTxtBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color ColorEnterTxtBox {
            get {
                return ((global::System.Drawing.Color)(this["ColorEnterTxtBox"]));
            }
            set {
                this["ColorEnterTxtBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User=SYSDBA;Password=masterkey;DataSource=localhost;Database=")]
        public string ConexaoFB {
            get {
                return ((string)(this["ConexaoFB"]));
            }
            set {
                this["ConexaoFB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IMEX Sistemas")]
        public string NomeEmpresa {
            get {
                return ((string)(this["NomeEmpresa"]));
            }
            set {
                this["NomeEmpresa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nota Fiscal de Consumidor Eletrônica - NFCe")]
        public string NameSytem {
            get {
                return ((string)(this["NameSytem"]));
            }
            set {
                this["NameSytem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy/MM/dd")]
        public string FormatDateSearch {
            get {
                return ((string)(this["FormatDateSearch"]));
            }
            set {
                this["FormatDateSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imexsistema.com.br")]
        public string site {
            get {
                return ((string)(this["site"]));
            }
            set {
                this["site"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imexsistema@gmail.com")]
        public string email {
            get {
                return ((string)(this["email"]));
            }
            set {
                this["email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TituloRelatorio {
            get {
                return ((string)(this["TituloRelatorio"]));
            }
            set {
                this["TituloRelatorio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string impressoraticket {
            get {
                return ((string)(this["impressoraticket"]));
            }
            set {
                this["impressoraticket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string msg1ticket {
            get {
                return ((string)(this["msg1ticket"]));
            }
            set {
                this["msg1ticket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string msg2ticket {
            get {
                return ((string)(this["msg2ticket"]));
            }
            set {
                this["msg2ticket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string msg3ticket {
            get {
                return ((string)(this["msg3ticket"]));
            }
            set {
                this["msg3ticket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string msg4ticket {
            get {
                return ((string)(this["msg4ticket"]));
            }
            set {
                this["msg4ticket"] = value;
            }
        }
    }
}
