//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class ConfigNFCe : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigNFCe defaultInstance = ((ConfigNFCe)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigNFCe())));
        
        public static ConfigNFCe Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string NaoPermitirEstoqueNegativo {
            get {
                return ((string)(this["NaoPermitirEstoqueNegativo"]));
            }
            set {
                this["NaoPermitirEstoqueNegativo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string NaoPermitirAlteraValorUnitário {
            get {
                return ((string)(this["NaoPermitirAlteraValorUnitário"]));
            }
            set {
                this["NaoPermitirAlteraValorUnitário"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string AdicionaProdutoAposLeituraCódigoBarra {
            get {
                return ((string)(this["AdicionaProdutoAposLeituraCódigoBarra"]));
            }
            set {
                this["AdicionaProdutoAposLeituraCódigoBarra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MaximizarTelaAbrir {
            get {
                return ((string)(this["MaximizarTelaAbrir"]));
            }
            set {
                this["MaximizarTelaAbrir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmitirSomAdicionarProduto {
            get {
                return ((string)(this["EmitirSomAdicionarProduto"]));
            }
            set {
                this["EmitirSomAdicionarProduto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PermitirDescontoFechamento {
            get {
                return ((string)(this["PermitirDescontoFechamento"]));
            }
            set {
                this["PermitirDescontoFechamento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IdCliente {
            get {
                return ((string)(this["IdCliente"]));
            }
            set {
                this["IdCliente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IdTipoPagamento {
            get {
                return ((string)(this["IdTipoPagamento"]));
            }
            set {
                this["IdTipoPagamento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IdFormaPagto {
            get {
                return ((string)(this["IdFormaPagto"]));
            }
            set {
                this["IdFormaPagto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IdCFOP {
            get {
                return ((string)(this["IdCFOP"]));
            }
            set {
                this["IdCFOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TipoImpressao {
            get {
                return ((string)(this["TipoImpressao"]));
            }
            set {
                this["TipoImpressao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VersaoSchema {
            get {
                return ((string)(this["VersaoSchema"]));
            }
            set {
                this["VersaoSchema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SerieNFCe {
            get {
                return ((string)(this["SerieNFCe"]));
            }
            set {
                this["SerieNFCe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PortaImpressora {
            get {
                return ((string)(this["PortaImpressora"]));
            }
            set {
                this["PortaImpressora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImpressoraSelecionada {
            get {
                return ((string)(this["ImpressoraSelecionada"]));
            }
            set {
                this["ImpressoraSelecionada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NaoExibirLegenda {
            get {
                return ((string)(this["NaoExibirLegenda"]));
            }
            set {
                this["NaoExibirLegenda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IdLocalCobranca {
            get {
                return ((string)(this["IdLocalCobranca"]));
            }
            set {
                this["IdLocalCobranca"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NaoPermitirValorUnitarioZerado {
            get {
                return ((string)(this["NaoPermitirValorUnitarioZerado"]));
            }
            set {
                this["NaoPermitirValorUnitarioZerado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NaoPermitirAlterarQuantidade {
            get {
                return ((string)(this["NaoPermitirAlterarQuantidade"]));
            }
            set {
                this["NaoPermitirAlterarQuantidade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NInicialNFCe {
            get {
                return ((string)(this["NInicialNFCe"]));
            }
            set {
                this["NInicialNFCe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IdentificacaoAmbiente {
            get {
                return ((string)(this["IdentificacaoAmbiente"]));
            }
            set {
                this["IdentificacaoAmbiente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TipoAutenticacao {
            get {
                return ((string)(this["TipoAutenticacao"]));
            }
            set {
                this["TipoAutenticacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathToSaveXml {
            get {
                return ((string)(this["PathToSaveXml"]));
            }
            set {
                this["PathToSaveXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginCryptPassd {
            get {
                return ((string)(this["LoginCryptPassd"]));
            }
            set {
                this["LoginCryptPassd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginUser {
            get {
                return ((string)(this["LoginUser"]));
            }
            set {
                this["LoginUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UrlNfCeService {
            get {
                return ((string)(this["UrlNfCeService"]));
            }
            set {
                this["UrlNfCeService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyAddress {
            get {
                return ((string)(this["ProxyAddress"]));
            }
            set {
                this["ProxyAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyUser {
            get {
                return ((string)(this["ProxyUser"]));
            }
            set {
                this["ProxyUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyPasswd {
            get {
                return ((string)(this["ProxyPasswd"]));
            }
            set {
                this["ProxyPasswd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProxyDomain {
            get {
                return ((string)(this["ProxyDomain"]));
            }
            set {
                this["ProxyDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Email {
            get {
                return ((string)(this["Email"]));
            }
            set {
                this["Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegimeTributarioCRT {
            get {
                return ((string)(this["RegimeTributarioCRT"]));
            }
            set {
                this["RegimeTributarioCRT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fundologo {
            get {
                return ((string)(this["fundologo"]));
            }
            set {
                this["fundologo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NomeFabImpressora {
            get {
                return ((string)(this["NomeFabImpressora"]));
            }
            set {
                this["NomeFabImpressora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmpresaIntegra {
            get {
                return ((string)(this["EmpresaIntegra"]));
            }
            set {
                this["EmpresaIntegra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalInstalacaoNewSystems {
            get {
                return ((string)(this["LocalInstalacaoNewSystems"]));
            }
            set {
                this["LocalInstalacaoNewSystems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiferencaFuxoHorario {
            get {
                return ((string)(this["DiferencaFuxoHorario"]));
            }
            set {
                this["DiferencaFuxoHorario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VersaoAplicativoNewsSystems {
            get {
                return ((string)(this["VersaoAplicativoNewsSystems"]));
            }
            set {
                this["VersaoAplicativoNewsSystems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CASADECPRINTDANFE {
            get {
                return ((string)(this["CASADECPRINTDANFE"]));
            }
            set {
                this["CASADECPRINTDANFE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CNPJCartaoVisa {
            get {
                return ((string)(this["CNPJCartaoVisa"]));
            }
            set {
                this["CNPJCartaoVisa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CNPJCartaoMarterCard {
            get {
                return ((string)(this["CNPJCartaoMarterCard"]));
            }
            set {
                this["CNPJCartaoMarterCard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CNPJCartaoAmericanExpress {
            get {
                return ((string)(this["CNPJCartaoAmericanExpress"]));
            }
            set {
                this["CNPJCartaoAmericanExpress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CNPJCartaoSorocred {
            get {
                return ((string)(this["CNPJCartaoSorocred"]));
            }
            set {
                this["CNPJCartaoSorocred"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CNPJCartaoOutros {
            get {
                return ((string)(this["CNPJCartaoOutros"]));
            }
            set {
                this["CNPJCartaoOutros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Transmitir {
            get {
                return ((string)(this["Transmitir"]));
            }
            set {
                this["Transmitir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModeloDocFiscal {
            get {
                return ((string)(this["ModeloDocFiscal"]));
            }
            set {
                this["ModeloDocFiscal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string impressoraticket {
            get {
                return ((string)(this["impressoraticket"]));
            }
            set {
                this["impressoraticket"] = value;
            }
        }
    }
}
