//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("teste Rafael")]
        public string teste {
            get {
                return ((string)(this["teste"]));
            }
            set {
                this["teste"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.soawebservices.com.br/webservices/test-drive/serasa/pefin.asmx")]
        public string IMEXSistema_br_com_soawebservices_www_SERASA {
            get {
                return ((string)(this["IMEXSistema_br_com_soawebservices_www_SERASA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.soawebservices.com.br/webservices/producao/sws/administracao.asmx")]
        public string IMEXSistema_Serasa_administracao_Administracao {
            get {
                return ((string)(this["IMEXSistema_Serasa_administracao_Administracao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://labs.soawebservices.com.br/webservices/test-drive/serasa/Concentre.asmx")]
        public string IMEXSistema_br_com_soawebservices_labs2_SERASA {
            get {
                return ((string)(this["IMEXSistema_br_com_soawebservices_labs2_SERASA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://labs.soawebservices.com.br/webservices/test-drive/serasa/cheques.asmx")]
        public string IMEXSistema_br_com_soawebservices_labs3_SERASA {
            get {
                return ((string)(this["IMEXSistema_br_com_soawebservices_labs3_SERASA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.soawebservices.com.br/webservices/test-drive/serasa/crednet.asmx")]
        public string IMEXSistema_br_com_soawebservices_www1_SERASA {
            get {
                return ((string)(this["IMEXSistema_br_com_soawebservices_www1_SERASA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.soawebservices.com.br/webservices/producao/sws/partners.asmx")]
        public string IMEXSistema_br_com_soawebservices_www2_Partners {
            get {
                return ((string)(this["IMEXSistema_br_com_soawebservices_www2_Partners"]));
            }
        }
    }
}
