//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BmsSoftware.br.com.soawebservices.www2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PartnersSoap", Namespace="SOAWebServices")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Serialization2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Serialization1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Serialization))]
    public partial class Partners : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CriaClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExtratoSimplificadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExtratoSimplificadoMensalOperationCompleted;
        
        private System.Threading.SendOrPostCallback CarregaCreditosViaBoletoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Partners() {
            this.Url = global::BmsSoftware.Properties.Settings.Default.IMEXSistema_br_com_soawebservices_www2_Partners;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CriaClienteCompletedEventHandler CriaClienteCompleted;
        
        /// <remarks/>
        public event ExtratoSimplificadoCompletedEventHandler ExtratoSimplificadoCompleted;
        
        /// <remarks/>
        public event ExtratoSimplificadoMensalCompletedEventHandler ExtratoSimplificadoMensalCompleted;
        
        /// <remarks/>
        public event CarregaCreditosViaBoletoCompletedEventHandler CarregaCreditosViaBoletoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/CriaCliente", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="urn:Cliente", IsNullable=true)]
        public Cliente1 CriaCliente(Credenciais Credenciais, Cliente Cliente) {
            object[] results = this.Invoke("CriaCliente", new object[] {
                        Credenciais,
                        Cliente});
            return ((Cliente1)(results[0]));
        }
        
        /// <remarks/>
        public void CriaClienteAsync(Credenciais Credenciais, Cliente Cliente) {
            this.CriaClienteAsync(Credenciais, Cliente, null);
        }
        
        /// <remarks/>
        public void CriaClienteAsync(Credenciais Credenciais, Cliente Cliente, object userState) {
            if ((this.CriaClienteOperationCompleted == null)) {
                this.CriaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCriaClienteOperationCompleted);
            }
            this.InvokeAsync("CriaCliente", new object[] {
                        Credenciais,
                        Cliente}, this.CriaClienteOperationCompleted, userState);
        }
        
        private void OnCriaClienteOperationCompleted(object arg) {
            if ((this.CriaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CriaClienteCompleted(this, new CriaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/ExtratoSimplificado", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExtratoSimplificado ExtratoSimplificado(Credenciais Credenciais) {
            object[] results = this.Invoke("ExtratoSimplificado", new object[] {
                        Credenciais});
            return ((ExtratoSimplificado)(results[0]));
        }
        
        /// <remarks/>
        public void ExtratoSimplificadoAsync(Credenciais Credenciais) {
            this.ExtratoSimplificadoAsync(Credenciais, null);
        }
        
        /// <remarks/>
        public void ExtratoSimplificadoAsync(Credenciais Credenciais, object userState) {
            if ((this.ExtratoSimplificadoOperationCompleted == null)) {
                this.ExtratoSimplificadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtratoSimplificadoOperationCompleted);
            }
            this.InvokeAsync("ExtratoSimplificado", new object[] {
                        Credenciais}, this.ExtratoSimplificadoOperationCompleted, userState);
        }
        
        private void OnExtratoSimplificadoOperationCompleted(object arg) {
            if ((this.ExtratoSimplificadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExtratoSimplificadoCompleted(this, new ExtratoSimplificadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/ExtratoSimplificadoMensal", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExtratoSimplificado ExtratoSimplificadoMensal(Credenciais Credenciais, string Mes, string Ano) {
            object[] results = this.Invoke("ExtratoSimplificadoMensal", new object[] {
                        Credenciais,
                        Mes,
                        Ano});
            return ((ExtratoSimplificado)(results[0]));
        }
        
        /// <remarks/>
        public void ExtratoSimplificadoMensalAsync(Credenciais Credenciais, string Mes, string Ano) {
            this.ExtratoSimplificadoMensalAsync(Credenciais, Mes, Ano, null);
        }
        
        /// <remarks/>
        public void ExtratoSimplificadoMensalAsync(Credenciais Credenciais, string Mes, string Ano, object userState) {
            if ((this.ExtratoSimplificadoMensalOperationCompleted == null)) {
                this.ExtratoSimplificadoMensalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtratoSimplificadoMensalOperationCompleted);
            }
            this.InvokeAsync("ExtratoSimplificadoMensal", new object[] {
                        Credenciais,
                        Mes,
                        Ano}, this.ExtratoSimplificadoMensalOperationCompleted, userState);
        }
        
        private void OnExtratoSimplificadoMensalOperationCompleted(object arg) {
            if ((this.ExtratoSimplificadoMensalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExtratoSimplificadoMensalCompleted(this, new ExtratoSimplificadoMensalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/CarregaCreditosViaBoleto", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="urn:Pagamentos", IsNullable=true)]
        public Pagamentos CarregaCreditosViaBoleto(Credenciais Credenciais, decimal ValorBoleto) {
            object[] results = this.Invoke("CarregaCreditosViaBoleto", new object[] {
                        Credenciais,
                        ValorBoleto});
            return ((Pagamentos)(results[0]));
        }
        
        /// <remarks/>
        public void CarregaCreditosViaBoletoAsync(Credenciais Credenciais, decimal ValorBoleto) {
            this.CarregaCreditosViaBoletoAsync(Credenciais, ValorBoleto, null);
        }
        
        /// <remarks/>
        public void CarregaCreditosViaBoletoAsync(Credenciais Credenciais, decimal ValorBoleto, object userState) {
            if ((this.CarregaCreditosViaBoletoOperationCompleted == null)) {
                this.CarregaCreditosViaBoletoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCarregaCreditosViaBoletoOperationCompleted);
            }
            this.InvokeAsync("CarregaCreditosViaBoleto", new object[] {
                        Credenciais,
                        ValorBoleto}, this.CarregaCreditosViaBoletoOperationCompleted, userState);
        }
        
        private void OnCarregaCreditosViaBoletoOperationCompleted(object arg) {
            if ((this.CarregaCreditosViaBoletoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CarregaCreditosViaBoletoCompleted(this, new CarregaCreditosViaBoletoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Credenciais {
        
        private string emailField;
        
        private string senhaField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pagamentos))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Serialization", Namespace="urn:Pagamentos")]
    public partial class Serialization2 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Pagamentos")]
    public partial class Pagamentos : Serialization2 {
        
        private string nossoNumeroField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string NossoNumero {
            get {
                return this.nossoNumeroField;
            }
            set {
                this.nossoNumeroField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Credenciais", Namespace="urn:Cliente")]
    public partial class Credenciais1 {
        
        private string emailField;
        
        private string senhaField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cliente1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Serialization", Namespace="urn:Cliente")]
    public partial class Serialization1 {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Cliente", Namespace="urn:Cliente")]
    public partial class Cliente1 : Serialization1 {
        
        private Credenciais1 credenciaisField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public Credenciais1 Credenciais {
            get {
                return this.credenciaisField;
            }
            set {
                this.credenciaisField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtratoDetalhe))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtratoSimplificado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Serialization {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class ExtratoDetalhe : Serialization {
        
        private string documentoField;
        
        private string nomeField;
        
        private decimal consumoValorField;
        
        private int consumoQuantidadeField;
        
        private decimal consumoComissaoField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ConsumoValor {
            get {
                return this.consumoValorField;
            }
            set {
                this.consumoValorField = value;
            }
        }
        
        /// <remarks/>
        public int ConsumoQuantidade {
            get {
                return this.consumoQuantidadeField;
            }
            set {
                this.consumoQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ConsumoComissao {
            get {
                return this.consumoComissaoField;
            }
            set {
                this.consumoComissaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class ExtratoSimplificado : Serialization {
        
        private int consumoQuantidadeTotalField;
        
        private decimal consumoValorTotalField;
        
        private decimal consumoComissaoTotalField;
        
        private ExtratoDetalhe[] extratoDetalheField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public int ConsumoQuantidadeTotal {
            get {
                return this.consumoQuantidadeTotalField;
            }
            set {
                this.consumoQuantidadeTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal ConsumoValorTotal {
            get {
                return this.consumoValorTotalField;
            }
            set {
                this.consumoValorTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal ConsumoComissaoTotal {
            get {
                return this.consumoComissaoTotalField;
            }
            set {
                this.consumoComissaoTotalField = value;
            }
        }
        
        /// <remarks/>
        public ExtratoDetalhe[] ExtratoDetalhe {
            get {
                return this.extratoDetalheField;
            }
            set {
                this.extratoDetalheField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Cliente : Serialization {
        
        private string documentoField;
        
        private string foneField;
        
        private string faxField;
        
        private string celularField;
        
        private string emailResponsavelField;
        
        private string emailFinanceiroField;
        
        private string emailNFSeField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Fone {
            get {
                return this.foneField;
            }
            set {
                this.foneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string EmailResponsavel {
            get {
                return this.emailResponsavelField;
            }
            set {
                this.emailResponsavelField = value;
            }
        }
        
        /// <remarks/>
        public string EmailFinanceiro {
            get {
                return this.emailFinanceiroField;
            }
            set {
                this.emailFinanceiroField = value;
            }
        }
        
        /// <remarks/>
        public string EmailNFSe {
            get {
                return this.emailNFSeField;
            }
            set {
                this.emailNFSeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CriaClienteCompletedEventHandler(object sender, CriaClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CriaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CriaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ExtratoSimplificadoCompletedEventHandler(object sender, ExtratoSimplificadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtratoSimplificadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExtratoSimplificadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtratoSimplificado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtratoSimplificado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ExtratoSimplificadoMensalCompletedEventHandler(object sender, ExtratoSimplificadoMensalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtratoSimplificadoMensalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExtratoSimplificadoMensalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtratoSimplificado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtratoSimplificado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CarregaCreditosViaBoletoCompletedEventHandler(object sender, CarregaCreditosViaBoletoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarregaCreditosViaBoletoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CarregaCreditosViaBoletoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pagamentos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pagamentos)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591