//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BmsSoftware.br.com.soawebservices.labs3 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SERASASoap", Namespace="SOAWebServices")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Serialization))]
    public partial class SERASA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChequeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SERASA() {
            this.Url = global::BmsSoftware.Properties.Settings.Default.IMEXSistema_br_com_soawebservices_labs3_SERASA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChequeCompletedEventHandler ChequeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/Cheque", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="urn:Cheques", IsNullable=true)]
        public Cheques Cheque(Credenciais Credenciais, string Documento, string Banco, string Agencia, string ContaCorrente, string NumeroChequeInicial, string NumeroChequeFinal) {
            object[] results = this.Invoke("Cheque", new object[] {
                        Credenciais,
                        Documento,
                        Banco,
                        Agencia,
                        ContaCorrente,
                        NumeroChequeInicial,
                        NumeroChequeFinal});
            return ((Cheques)(results[0]));
        }
        
        /// <remarks/>
        public void ChequeAsync(Credenciais Credenciais, string Documento, string Banco, string Agencia, string ContaCorrente, string NumeroChequeInicial, string NumeroChequeFinal) {
            this.ChequeAsync(Credenciais, Documento, Banco, Agencia, ContaCorrente, NumeroChequeInicial, NumeroChequeFinal, null);
        }
        
        /// <remarks/>
        public void ChequeAsync(Credenciais Credenciais, string Documento, string Banco, string Agencia, string ContaCorrente, string NumeroChequeInicial, string NumeroChequeFinal, object userState) {
            if ((this.ChequeOperationCompleted == null)) {
                this.ChequeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChequeOperationCompleted);
            }
            this.InvokeAsync("Cheque", new object[] {
                        Credenciais,
                        Documento,
                        Banco,
                        Agencia,
                        ContaCorrente,
                        NumeroChequeInicial,
                        NumeroChequeFinal}, this.ChequeOperationCompleted, userState);
        }
        
        private void OnChequeOperationCompleted(object arg) {
            if ((this.ChequeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChequeCompleted(this, new ChequeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Credenciais {
        
        private string emailField;
        
        private string senhaField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class AgenciaBancariaEndereco {
        
        private string logradouroField;
        
        private string cidadeField;
        
        private string estadoField;
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class AgenciaBancariaResumo {
        
        private string nomeAgenciaField;
        
        private string dataUltimaAtualizacaoField;
        
        private string foneField;
        
        private string faxField;
        
        /// <remarks/>
        public string NomeAgencia {
            get {
                return this.nomeAgenciaField;
            }
            set {
                this.nomeAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string DataUltimaAtualizacao {
            get {
                return this.dataUltimaAtualizacaoField;
            }
            set {
                this.dataUltimaAtualizacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Fone {
            get {
                return this.foneField;
            }
            set {
                this.foneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class AgenciaBancaria {
        
        private AgenciaBancariaResumo agenciaBancariaResumoField;
        
        private AgenciaBancariaEndereco agenciaBancariaEnderecoField;
        
        private string mensagemField;
        
        /// <remarks/>
        public AgenciaBancariaResumo AgenciaBancariaResumo {
            get {
                return this.agenciaBancariaResumoField;
            }
            set {
                this.agenciaBancariaResumoField = value;
            }
        }
        
        /// <remarks/>
        public AgenciaBancariaEndereco AgenciaBancariaEndereco {
            get {
                return this.agenciaBancariaEnderecoField;
            }
            set {
                this.agenciaBancariaEnderecoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class HistoricoContaCorrente {
        
        private string tipoDocumentoField;
        
        private string documentoField;
        
        private string nomeField;
        
        private int quantidadeConsultasField;
        
        private string dataOcorrenciaMaisAntigaField;
        
        private string dataOcorrenciaMaisRecenteField;
        
        private string ultimaEmpresaConsultanteField;
        
        /// <remarks/>
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public int QuantidadeConsultas {
            get {
                return this.quantidadeConsultasField;
            }
            set {
                this.quantidadeConsultasField = value;
            }
        }
        
        /// <remarks/>
        public string DataOcorrenciaMaisAntiga {
            get {
                return this.dataOcorrenciaMaisAntigaField;
            }
            set {
                this.dataOcorrenciaMaisAntigaField = value;
            }
        }
        
        /// <remarks/>
        public string DataOcorrenciaMaisRecente {
            get {
                return this.dataOcorrenciaMaisRecenteField;
            }
            set {
                this.dataOcorrenciaMaisRecenteField = value;
            }
        }
        
        /// <remarks/>
        public string UltimaEmpresaConsultante {
            get {
                return this.ultimaEmpresaConsultanteField;
            }
            set {
                this.ultimaEmpresaConsultanteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class HistoricoDadoCadastral {
        
        private string tipoDocumentoField;
        
        private string documentoField;
        
        private string nomeField;
        
        private int quantidadeConsultasField;
        
        private string dataOcorrenciaMaisAntigaField;
        
        private string dataOcorrenciaMaisRecenteField;
        
        private string ultimaEmpresaConsultanteField;
        
        /// <remarks/>
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public int QuantidadeConsultas {
            get {
                return this.quantidadeConsultasField;
            }
            set {
                this.quantidadeConsultasField = value;
            }
        }
        
        /// <remarks/>
        public string DataOcorrenciaMaisAntiga {
            get {
                return this.dataOcorrenciaMaisAntigaField;
            }
            set {
                this.dataOcorrenciaMaisAntigaField = value;
            }
        }
        
        /// <remarks/>
        public string DataOcorrenciaMaisRecente {
            get {
                return this.dataOcorrenciaMaisRecenteField;
            }
            set {
                this.dataOcorrenciaMaisRecenteField = value;
            }
        }
        
        /// <remarks/>
        public string UltimaEmpresaConsultante {
            get {
                return this.ultimaEmpresaConsultanteField;
            }
            set {
                this.ultimaEmpresaConsultanteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class HistoricoResumo {
        
        private string numeroChequeField;
        
        private int totalConsultasChequeField;
        
        private string dataConsultaMaisAntigaField;
        
        private string dataConsultaMaisRecenteField;
        
        private string ultimaEmpresaConsultanteField;
        
        private int quantidadeDadoCadastralField;
        
        private int quantidadeContaCorrenteField;
        
        /// <remarks/>
        public string NumeroCheque {
            get {
                return this.numeroChequeField;
            }
            set {
                this.numeroChequeField = value;
            }
        }
        
        /// <remarks/>
        public int TotalConsultasCheque {
            get {
                return this.totalConsultasChequeField;
            }
            set {
                this.totalConsultasChequeField = value;
            }
        }
        
        /// <remarks/>
        public string DataConsultaMaisAntiga {
            get {
                return this.dataConsultaMaisAntigaField;
            }
            set {
                this.dataConsultaMaisAntigaField = value;
            }
        }
        
        /// <remarks/>
        public string DataConsultaMaisRecente {
            get {
                return this.dataConsultaMaisRecenteField;
            }
            set {
                this.dataConsultaMaisRecenteField = value;
            }
        }
        
        /// <remarks/>
        public string UltimaEmpresaConsultante {
            get {
                return this.ultimaEmpresaConsultanteField;
            }
            set {
                this.ultimaEmpresaConsultanteField = value;
            }
        }
        
        /// <remarks/>
        public int QuantidadeDadoCadastral {
            get {
                return this.quantidadeDadoCadastralField;
            }
            set {
                this.quantidadeDadoCadastralField = value;
            }
        }
        
        /// <remarks/>
        public int QuantidadeContaCorrente {
            get {
                return this.quantidadeContaCorrenteField;
            }
            set {
                this.quantidadeContaCorrenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class Historicos {
        
        private HistoricoResumo resumoField;
        
        private HistoricoDadoCadastral[] dadosCadastraisField;
        
        private HistoricoContaCorrente[] contaCorrenteField;
        
        private string mensagemField;
        
        /// <remarks/>
        public HistoricoResumo Resumo {
            get {
                return this.resumoField;
            }
            set {
                this.resumoField = value;
            }
        }
        
        /// <remarks/>
        public HistoricoDadoCadastral[] DadosCadastrais {
            get {
                return this.dadosCadastraisField;
            }
            set {
                this.dadosCadastraisField = value;
            }
        }
        
        /// <remarks/>
        public HistoricoContaCorrente[] ContaCorrente {
            get {
                return this.contaCorrenteField;
            }
            set {
                this.contaCorrenteField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class ContumaciaDetalhe {
        
        private string codigoCompensacaoField;
        
        private string agenciaField;
        
        private string contaCorrenteField;
        
        private string numeroChequeInicialField;
        
        private string numeroChequeFinalField;
        
        private ContumaciaMotivos motivoField;
        
        private string dataOcorrenciaField;
        
        private string codigoDaFonteField;
        
        /// <remarks/>
        public string CodigoCompensacao {
            get {
                return this.codigoCompensacaoField;
            }
            set {
                this.codigoCompensacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string ContaCorrente {
            get {
                return this.contaCorrenteField;
            }
            set {
                this.contaCorrenteField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroChequeInicial {
            get {
                return this.numeroChequeInicialField;
            }
            set {
                this.numeroChequeInicialField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroChequeFinal {
            get {
                return this.numeroChequeFinalField;
            }
            set {
                this.numeroChequeFinalField = value;
            }
        }
        
        /// <remarks/>
        public ContumaciaMotivos Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoDaFonte {
            get {
                return this.codigoDaFonteField;
            }
            set {
                this.codigoDaFonteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public enum ContumaciaMotivos {
        
        /// <remarks/>
        SUSTADO,
        
        /// <remarks/>
        EXTRAVIADO,
        
        /// <remarks/>
        CANCELADO,
        
        /// <remarks/>
        ROUBADO,
        
        /// <remarks/>
        BLOQUEADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class ContumaciaResumo {
        
        private int totalOcorrenciasField;
        
        private string ocorrenciaMaisAntigaField;
        
        private string ocorrenciaMaisRecenteField;
        
        private ContumaciaDetalhe[] contumaciaDetalheField;
        
        private string mensagemField;
        
        /// <remarks/>
        public int TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public string OcorrenciaMaisAntiga {
            get {
                return this.ocorrenciaMaisAntigaField;
            }
            set {
                this.ocorrenciaMaisAntigaField = value;
            }
        }
        
        /// <remarks/>
        public string OcorrenciaMaisRecente {
            get {
                return this.ocorrenciaMaisRecenteField;
            }
            set {
                this.ocorrenciaMaisRecenteField = value;
            }
        }
        
        /// <remarks/>
        public ContumaciaDetalhe[] ContumaciaDetalhe {
            get {
                return this.contumaciaDetalheField;
            }
            set {
                this.contumaciaDetalheField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class Contumacia {
        
        private ContumaciaResumo consumaciaResumoField;
        
        private ContumaciaDetalhe[] contumaciaDetalheField;
        
        private string mensagemField;
        
        /// <remarks/>
        public ContumaciaResumo ConsumaciaResumo {
            get {
                return this.consumaciaResumoField;
            }
            set {
                this.consumaciaResumoField = value;
            }
        }
        
        /// <remarks/>
        public ContumaciaDetalhe[] ContumaciaDetalhe {
            get {
                return this.contumaciaDetalheField;
            }
            set {
                this.contumaciaDetalheField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class PendenciasBacenDetalhe {
        
        private string dataOcorrenciaField;
        
        private string numeroChequeField;
        
        private string alineaChequeField;
        
        private string quantidadeCCFBancoField;
        
        private string valorField;
        
        private string bancoField;
        
        private string agenciaField;
        
        private string cidadeField;
        
        private string ufField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCheque {
            get {
                return this.numeroChequeField;
            }
            set {
                this.numeroChequeField = value;
            }
        }
        
        /// <remarks/>
        public string AlineaCheque {
            get {
                return this.alineaChequeField;
            }
            set {
                this.alineaChequeField = value;
            }
        }
        
        /// <remarks/>
        public string QuantidadeCCFBanco {
            get {
                return this.quantidadeCCFBancoField;
            }
            set {
                this.quantidadeCCFBancoField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        public string Agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class PendenciasBacen {
        
        private int totalOcorrenciasField;
        
        private string ocorrenciaMaisAntigaField;
        
        private string ocorrenciaMaisRecenteField;
        
        private string bancoField;
        
        private string agenciaField;
        
        private string nomeFantasiaBancoField;
        
        private PendenciasBacenDetalhe[] pendenciasBacenDetalheField;
        
        private string mensagemField;
        
        /// <remarks/>
        public int TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public string OcorrenciaMaisAntiga {
            get {
                return this.ocorrenciaMaisAntigaField;
            }
            set {
                this.ocorrenciaMaisAntigaField = value;
            }
        }
        
        /// <remarks/>
        public string OcorrenciaMaisRecente {
            get {
                return this.ocorrenciaMaisRecenteField;
            }
            set {
                this.ocorrenciaMaisRecenteField = value;
            }
        }
        
        /// <remarks/>
        public string Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        public string Agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string NomeFantasiaBanco {
            get {
                return this.nomeFantasiaBancoField;
            }
            set {
                this.nomeFantasiaBancoField = value;
            }
        }
        
        /// <remarks/>
        public PendenciasBacenDetalhe[] PendenciasBacenDetalhe {
            get {
                return this.pendenciasBacenDetalheField;
            }
            set {
                this.pendenciasBacenDetalheField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class PendenciasFinanceirasDetalhe {
        
        private string dataOcorrenciaField;
        
        private string modalidadeField;
        
        private string avalistaField;
        
        private string tipoMoedaField;
        
        private decimal valorField;
        
        private string contratoField;
        
        private string origemField;
        
        private string siglaField;
        
        private string subJudiceField;
        
        private string subJudiceDescricaoField;
        
        private string tipoAnotacaoField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Modalidade {
            get {
                return this.modalidadeField;
            }
            set {
                this.modalidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Avalista {
            get {
                return this.avalistaField;
            }
            set {
                this.avalistaField = value;
            }
        }
        
        /// <remarks/>
        public string TipoMoeda {
            get {
                return this.tipoMoedaField;
            }
            set {
                this.tipoMoedaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string Contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
            }
        }
        
        /// <remarks/>
        public string Origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
            }
        }
        
        /// <remarks/>
        public string Sigla {
            get {
                return this.siglaField;
            }
            set {
                this.siglaField = value;
            }
        }
        
        /// <remarks/>
        public string SubJudice {
            get {
                return this.subJudiceField;
            }
            set {
                this.subJudiceField = value;
            }
        }
        
        /// <remarks/>
        public string SubJudiceDescricao {
            get {
                return this.subJudiceDescricaoField;
            }
            set {
                this.subJudiceDescricaoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoAnotacao {
            get {
                return this.tipoAnotacaoField;
            }
            set {
                this.tipoAnotacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class PendenciasFinanceiras {
        
        private int totalOcorrenciasField;
        
        private string ocorrenciaMaisAntigaField;
        
        private string ocorrenciaMaisRecenteField;
        
        private string valorTotalOcorrenciasField;
        
        private PendenciasFinanceirasDetalhe[] pendenciasFinanceirasDetalheField;
        
        private string mensagemField;
        
        /// <remarks/>
        public int TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public string OcorrenciaMaisAntiga {
            get {
                return this.ocorrenciaMaisAntigaField;
            }
            set {
                this.ocorrenciaMaisAntigaField = value;
            }
        }
        
        /// <remarks/>
        public string OcorrenciaMaisRecente {
            get {
                return this.ocorrenciaMaisRecenteField;
            }
            set {
                this.ocorrenciaMaisRecenteField = value;
            }
        }
        
        /// <remarks/>
        public string ValorTotalOcorrencias {
            get {
                return this.valorTotalOcorrenciasField;
            }
            set {
                this.valorTotalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public PendenciasFinanceirasDetalhe[] PendenciasFinanceirasDetalhe {
            get {
                return this.pendenciasFinanceirasDetalheField;
            }
            set {
                this.pendenciasFinanceirasDetalheField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class PendenciasInternasDetalhe {
        
        private string dataOcorrenciaField;
        
        private string modalidadeField;
        
        private string avalistaField;
        
        private string tipoMoedaField;
        
        private decimal valorField;
        
        private string contratoField;
        
        private string origemField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Modalidade {
            get {
                return this.modalidadeField;
            }
            set {
                this.modalidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Avalista {
            get {
                return this.avalistaField;
            }
            set {
                this.avalistaField = value;
            }
        }
        
        /// <remarks/>
        public string TipoMoeda {
            get {
                return this.tipoMoedaField;
            }
            set {
                this.tipoMoedaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string Contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
            }
        }
        
        /// <remarks/>
        public string Origem {
            get {
                return this.origemField;
            }
            set {
                this.origemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class PendenciasInternas {
        
        private int totalOcorrenciasField;
        
        private string ocorrenciaMaisAntigaField;
        
        private string ocorrenciaMaisRecenteField;
        
        private string valorTotalOcorrenciasField;
        
        private PendenciasInternasDetalhe[] pendenciasIternasDetalheField;
        
        private string mensagemField;
        
        /// <remarks/>
        public int TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public string OcorrenciaMaisAntiga {
            get {
                return this.ocorrenciaMaisAntigaField;
            }
            set {
                this.ocorrenciaMaisAntigaField = value;
            }
        }
        
        /// <remarks/>
        public string OcorrenciaMaisRecente {
            get {
                return this.ocorrenciaMaisRecenteField;
            }
            set {
                this.ocorrenciaMaisRecenteField = value;
            }
        }
        
        /// <remarks/>
        public string ValorTotalOcorrencias {
            get {
                return this.valorTotalOcorrenciasField;
            }
            set {
                this.valorTotalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public PendenciasInternasDetalhe[] PendenciasIternasDetalhe {
            get {
                return this.pendenciasIternasDetalheField;
            }
            set {
                this.pendenciasIternasDetalheField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class ChequeDetalhe {
        
        private string bancoField;
        
        private string agenciaField;
        
        private string contaCorrenteField;
        
        private string numeroChequeField;
        
        private ChequeMotivos motivoField;
        
        private string dataCadastroField;
        
        private string horaCadastroField;
        
        private string codigoDaFonteField;
        
        /// <remarks/>
        public string Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        public string Agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string ContaCorrente {
            get {
                return this.contaCorrenteField;
            }
            set {
                this.contaCorrenteField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCheque {
            get {
                return this.numeroChequeField;
            }
            set {
                this.numeroChequeField = value;
            }
        }
        
        /// <remarks/>
        public ChequeMotivos Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        public string DataCadastro {
            get {
                return this.dataCadastroField;
            }
            set {
                this.dataCadastroField = value;
            }
        }
        
        /// <remarks/>
        public string HoraCadastro {
            get {
                return this.horaCadastroField;
            }
            set {
                this.horaCadastroField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoDaFonte {
            get {
                return this.codigoDaFonteField;
            }
            set {
                this.codigoDaFonteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public enum ChequeMotivos {
        
        /// <remarks/>
        SUSTADO,
        
        /// <remarks/>
        EXTRAVIADO,
        
        /// <remarks/>
        CANCELADO,
        
        /// <remarks/>
        ROUBADO,
        
        /// <remarks/>
        BLOQUEADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class ChequesResumo {
        
        private int totalOcorrenciasField;
        
        private string nomeFantasiaBancoField;
        
        private string mensagemField;
        
        private ChequeDetalhe[] chequeDetalheField;
        
        /// <remarks/>
        public int TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public string NomeFantasiaBanco {
            get {
                return this.nomeFantasiaBancoField;
            }
            set {
                this.nomeFantasiaBancoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public ChequeDetalhe[] ChequeDetalhe {
            get {
                return this.chequeDetalheField;
            }
            set {
                this.chequeDetalheField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class TelefonesContato {
        
        private string telefoneField;
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class AlertaDeDocumentos {
        
        private string numeroMensagemField;
        
        private string totalMensagensField;
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string motivoOcorrenciaField;
        
        private string dataOcorrenciaField;
        
        private TelefonesContato[] telefonesContatoField;
        
        private string mensagemField;
        
        /// <remarks/>
        public string NumeroMensagem {
            get {
                return this.numeroMensagemField;
            }
            set {
                this.numeroMensagemField = value;
            }
        }
        
        /// <remarks/>
        public string TotalMensagens {
            get {
                return this.totalMensagensField;
            }
            set {
                this.totalMensagensField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string MotivoOcorrencia {
            get {
                return this.motivoOcorrenciaField;
            }
            set {
                this.motivoOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public TelefonesContato[] TelefonesContato {
            get {
                return this.telefonesContatoField;
            }
            set {
                this.telefonesContatoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class SinteseCadastral {
        
        private string documentoField;
        
        private string nomeField;
        
        private string nomeMaeField;
        
        private string dataNascimentoField;
        
        private string situacaoRFBField;
        
        private string situacaoDescricaoRFBField;
        
        private string dataSituacaoRFBField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoRFB {
            get {
                return this.situacaoRFBField;
            }
            set {
                this.situacaoRFBField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoDescricaoRFB {
            get {
                return this.situacaoDescricaoRFBField;
            }
            set {
                this.situacaoDescricaoRFBField = value;
            }
        }
        
        /// <remarks/>
        public string DataSituacaoRFB {
            get {
                return this.dataSituacaoRFBField;
            }
            set {
                this.dataSituacaoRFBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cheques))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class Serialization {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:Cheques")]
    public partial class Cheques : Serialization {
        
        private SinteseCadastral sinteseCadastralField;
        
        private AlertaDeDocumentos alertadeDocumentosField;
        
        private ChequesResumo chequesResumoField;
        
        private PendenciasInternas pendenciasInternasField;
        
        private PendenciasFinanceiras pendenciasFinanceirasField;
        
        private PendenciasBacen pendenciasBacenField;
        
        private Contumacia contumaciasField;
        
        private Historicos historicosField;
        
        private AgenciaBancaria agenciaBancariaField;
        
        private string totalOcorrenciasField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public SinteseCadastral SinteseCadastral {
            get {
                return this.sinteseCadastralField;
            }
            set {
                this.sinteseCadastralField = value;
            }
        }
        
        /// <remarks/>
        public AlertaDeDocumentos AlertadeDocumentos {
            get {
                return this.alertadeDocumentosField;
            }
            set {
                this.alertadeDocumentosField = value;
            }
        }
        
        /// <remarks/>
        public ChequesResumo ChequesResumo {
            get {
                return this.chequesResumoField;
            }
            set {
                this.chequesResumoField = value;
            }
        }
        
        /// <remarks/>
        public PendenciasInternas PendenciasInternas {
            get {
                return this.pendenciasInternasField;
            }
            set {
                this.pendenciasInternasField = value;
            }
        }
        
        /// <remarks/>
        public PendenciasFinanceiras PendenciasFinanceiras {
            get {
                return this.pendenciasFinanceirasField;
            }
            set {
                this.pendenciasFinanceirasField = value;
            }
        }
        
        /// <remarks/>
        public PendenciasBacen PendenciasBacen {
            get {
                return this.pendenciasBacenField;
            }
            set {
                this.pendenciasBacenField = value;
            }
        }
        
        /// <remarks/>
        public Contumacia Contumacias {
            get {
                return this.contumaciasField;
            }
            set {
                this.contumaciasField = value;
            }
        }
        
        /// <remarks/>
        public Historicos Historicos {
            get {
                return this.historicosField;
            }
            set {
                this.historicosField = value;
            }
        }
        
        /// <remarks/>
        public AgenciaBancaria AgenciaBancaria {
            get {
                return this.agenciaBancariaField;
            }
            set {
                this.agenciaBancariaField = value;
            }
        }
        
        /// <remarks/>
        public string TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ChequeCompletedEventHandler(object sender, ChequeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChequeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChequeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cheques Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cheques)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591