//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BmsSoftware.br.com.soawebservices.labs2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SERASASoap", Namespace="SOAWebServices")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Serialization))]
    public partial class SERASA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConcentreOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SERASA() {
            this.Url = global::BmsSoftware.Properties.Settings.Default.IMEXSistema_br_com_soawebservices_labs2_SERASA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConcentreCompletedEventHandler ConcentreCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/Concentre", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Concentre Concentre(Credenciais Credenciais, string Documento) {
            object[] results = this.Invoke("Concentre", new object[] {
                        Credenciais,
                        Documento});
            return ((Concentre)(results[0]));
        }
        
        /// <remarks/>
        public void ConcentreAsync(Credenciais Credenciais, string Documento) {
            this.ConcentreAsync(Credenciais, Documento, null);
        }
        
        /// <remarks/>
        public void ConcentreAsync(Credenciais Credenciais, string Documento, object userState) {
            if ((this.ConcentreOperationCompleted == null)) {
                this.ConcentreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConcentreOperationCompleted);
            }
            this.InvokeAsync("Concentre", new object[] {
                        Credenciais,
                        Documento}, this.ConcentreOperationCompleted, userState);
        }
        
        private void OnConcentreOperationCompleted(object arg) {
            if ((this.ConcentreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConcentreCompleted(this, new ConcentreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Credenciais {
        
        private string emailField;
        
        private string senhaField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Alerta {
        
        private string totalMensagensField;
        
        private string mensagemField;
        
        /// <remarks/>
        public string TotalMensagens {
            get {
                return this.totalMensagensField;
            }
            set {
                this.totalMensagensField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Convem {
        
        private string dataOcorrenciaField;
        
        private string codigoNaturezaField;
        
        private string descricaoNaturezaField;
        
        private string valorField;
        
        private string numeroLojaFilialField;
        
        private string localidadeField;
        
        private string estadoField;
        
        private string cNPJCredorField;
        
        private string credorField;
        
        private string contratoField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoNatureza {
            get {
                return this.codigoNaturezaField;
            }
            set {
                this.codigoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoNatureza {
            get {
                return this.descricaoNaturezaField;
            }
            set {
                this.descricaoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroLojaFilial {
            get {
                return this.numeroLojaFilialField;
            }
            set {
                this.numeroLojaFilialField = value;
            }
        }
        
        /// <remarks/>
        public string Localidade {
            get {
                return this.localidadeField;
            }
            set {
                this.localidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJCredor {
            get {
                return this.cNPJCredorField;
            }
            set {
                this.cNPJCredorField = value;
            }
        }
        
        /// <remarks/>
        public string Credor {
            get {
                return this.credorField;
            }
            set {
                this.credorField = value;
            }
        }
        
        /// <remarks/>
        public string Contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class PendenciaFinanceira {
        
        private string dataOcorrenciaField;
        
        private string codigoNaturezaField;
        
        private string descricaoNaturezaField;
        
        private string valorField;
        
        private string localidadeField;
        
        private string estadoField;
        
        private string cNPJCredorField;
        
        private string credorField;
        
        private string avalistaField;
        
        private string contratoField;
        
        private string subJudiceField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoNatureza {
            get {
                return this.codigoNaturezaField;
            }
            set {
                this.codigoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoNatureza {
            get {
                return this.descricaoNaturezaField;
            }
            set {
                this.descricaoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string Localidade {
            get {
                return this.localidadeField;
            }
            set {
                this.localidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJCredor {
            get {
                return this.cNPJCredorField;
            }
            set {
                this.cNPJCredorField = value;
            }
        }
        
        /// <remarks/>
        public string Credor {
            get {
                return this.credorField;
            }
            set {
                this.credorField = value;
            }
        }
        
        /// <remarks/>
        public string Avalista {
            get {
                return this.avalistaField;
            }
            set {
                this.avalistaField = value;
            }
        }
        
        /// <remarks/>
        public string Contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
            }
        }
        
        /// <remarks/>
        public string SubJudice {
            get {
                return this.subJudiceField;
            }
            set {
                this.subJudiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class CCF {
        
        private string dataOcorrenciaField;
        
        private string codigoBancoField;
        
        private string nomeFantasiaBancoField;
        
        private string numeroAgenciaField;
        
        private string naturezadaContaField;
        
        private string totalChequesField;
        
        private string localidadeField;
        
        private string estadoField;
        
        private string cidadeField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoBanco {
            get {
                return this.codigoBancoField;
            }
            set {
                this.codigoBancoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeFantasiaBanco {
            get {
                return this.nomeFantasiaBancoField;
            }
            set {
                this.nomeFantasiaBancoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroAgencia {
            get {
                return this.numeroAgenciaField;
            }
            set {
                this.numeroAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string NaturezadaConta {
            get {
                return this.naturezadaContaField;
            }
            set {
                this.naturezadaContaField = value;
            }
        }
        
        /// <remarks/>
        public string TotalCheques {
            get {
                return this.totalChequesField;
            }
            set {
                this.totalChequesField = value;
            }
        }
        
        /// <remarks/>
        public string Localidade {
            get {
                return this.localidadeField;
            }
            set {
                this.localidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Achei {
        
        private string dataOcorrenciaField;
        
        private string codigoBancoField;
        
        private string codigoAgenciaField;
        
        private string contaCorrenteField;
        
        private string codigoNaturezaField;
        
        private string descricaoNaturezaField;
        
        private string valorField;
        
        private string localidadeField;
        
        private string estadoField;
        
        private string cidadeField;
        
        private string nomeBancoField;
        
        private string numeroChequeField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoBanco {
            get {
                return this.codigoBancoField;
            }
            set {
                this.codigoBancoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoAgencia {
            get {
                return this.codigoAgenciaField;
            }
            set {
                this.codigoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string ContaCorrente {
            get {
                return this.contaCorrenteField;
            }
            set {
                this.contaCorrenteField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoNatureza {
            get {
                return this.codigoNaturezaField;
            }
            set {
                this.codigoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoNatureza {
            get {
                return this.descricaoNaturezaField;
            }
            set {
                this.descricaoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string Localidade {
            get {
                return this.localidadeField;
            }
            set {
                this.localidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string NomeBanco {
            get {
                return this.nomeBancoField;
            }
            set {
                this.nomeBancoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCheque {
            get {
                return this.numeroChequeField;
            }
            set {
                this.numeroChequeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class RestricaoFinanceira {
        
        private string dataOcorrenciaField;
        
        private string codigoNaturezaField;
        
        private string descricaoNaturezaField;
        
        private string codigoBancoField;
        
        private string codigoAgenciaField;
        
        private string nomeBancoField;
        
        private string valorField;
        
        private string localidadeField;
        
        private string estadoField;
        
        private string cidadeField;
        
        private string avalistaField;
        
        private string subJudiceField;
        
        private string cNPJField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoNatureza {
            get {
                return this.codigoNaturezaField;
            }
            set {
                this.codigoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoNatureza {
            get {
                return this.descricaoNaturezaField;
            }
            set {
                this.descricaoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoBanco {
            get {
                return this.codigoBancoField;
            }
            set {
                this.codigoBancoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoAgencia {
            get {
                return this.codigoAgenciaField;
            }
            set {
                this.codigoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string NomeBanco {
            get {
                return this.nomeBancoField;
            }
            set {
                this.nomeBancoField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string Localidade {
            get {
                return this.localidadeField;
            }
            set {
                this.localidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Avalista {
            get {
                return this.avalistaField;
            }
            set {
                this.avalistaField = value;
            }
        }
        
        /// <remarks/>
        public string SubJudice {
            get {
                return this.subJudiceField;
            }
            set {
                this.subJudiceField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class ParticipacaoFalencia {
        
        private string dataOcorrenciaField;
        
        private string codigoNaturezaField;
        
        private string descricaoNaturezaField;
        
        private string codigoQualificacaoField;
        
        private string numeroVaraCivelField;
        
        private string cNPJField;
        
        private string razaoSocialField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoNatureza {
            get {
                return this.codigoNaturezaField;
            }
            set {
                this.codigoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoNatureza {
            get {
                return this.descricaoNaturezaField;
            }
            set {
                this.descricaoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoQualificacao {
            get {
                return this.codigoQualificacaoField;
            }
            set {
                this.codigoQualificacaoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroVaraCivel {
            get {
                return this.numeroVaraCivelField;
            }
            set {
                this.numeroVaraCivelField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class FalenciaConcordata {
        
        private string dataOcorrenciaField;
        
        private string codigoNaturezaField;
        
        private string descricaoNaturezaField;
        
        private string numeroVaraCivelField;
        
        private string localidadeField;
        
        private string estadoField;
        
        private string cidadeField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoNatureza {
            get {
                return this.codigoNaturezaField;
            }
            set {
                this.codigoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoNatureza {
            get {
                return this.descricaoNaturezaField;
            }
            set {
                this.descricaoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroVaraCivel {
            get {
                return this.numeroVaraCivelField;
            }
            set {
                this.numeroVaraCivelField = value;
            }
        }
        
        /// <remarks/>
        public string Localidade {
            get {
                return this.localidadeField;
            }
            set {
                this.localidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class AcaoJudicial {
        
        private string dataOcorrenciaField;
        
        private string numeroVaraCivelField;
        
        private string numeroDistribuidorField;
        
        private string codigoNaturezaField;
        
        private string descricaoNaturezaField;
        
        private string valorField;
        
        private string localidadeField;
        
        private string estadoField;
        
        private string cidadeField;
        
        private string principalField;
        
        private string subJudiceField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroVaraCivel {
            get {
                return this.numeroVaraCivelField;
            }
            set {
                this.numeroVaraCivelField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroDistribuidor {
            get {
                return this.numeroDistribuidorField;
            }
            set {
                this.numeroDistribuidorField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoNatureza {
            get {
                return this.codigoNaturezaField;
            }
            set {
                this.codigoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoNatureza {
            get {
                return this.descricaoNaturezaField;
            }
            set {
                this.descricaoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string Localidade {
            get {
                return this.localidadeField;
            }
            set {
                this.localidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <remarks/>
        public string SubJudice {
            get {
                return this.subJudiceField;
            }
            set {
                this.subJudiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Protesto {
        
        private string dataOcorrenciaField;
        
        private string numeroCartorioField;
        
        private string codigoNaturezaField;
        
        private string descricaoNaturezaField;
        
        private string valorField;
        
        private string localidadeField;
        
        private string estadoField;
        
        private string cidadeField;
        
        private string subJudiceField;
        
        private string dataCartaAnuenciaField;
        
        /// <remarks/>
        public string DataOcorrencia {
            get {
                return this.dataOcorrenciaField;
            }
            set {
                this.dataOcorrenciaField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCartorio {
            get {
                return this.numeroCartorioField;
            }
            set {
                this.numeroCartorioField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoNatureza {
            get {
                return this.codigoNaturezaField;
            }
            set {
                this.codigoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoNatureza {
            get {
                return this.descricaoNaturezaField;
            }
            set {
                this.descricaoNaturezaField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string Localidade {
            get {
                return this.localidadeField;
            }
            set {
                this.localidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string SubJudice {
            get {
                return this.subJudiceField;
            }
            set {
                this.subJudiceField = value;
            }
        }
        
        /// <remarks/>
        public string DataCartaAnuencia {
            get {
                return this.dataCartaAnuenciaField;
            }
            set {
                this.dataCartaAnuenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Grafias {
        
        private string grafiaField;
        
        /// <remarks/>
        public string Grafia {
            get {
                return this.grafiaField;
            }
            set {
                this.grafiaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Concentre))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Serialization {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Concentre : Serialization {
        
        private string documentoField;
        
        private string nomeField;
        
        private string situacaoDocumentoField;
        
        private string nomeMaeField;
        
        private string dataNascimentoField;
        
        private string totalOcorrenciasField;
        
        private Grafias[] grafiasField;
        
        private Protesto[] protestosField;
        
        private AcaoJudicial[] acoesJudiciaisField;
        
        private FalenciaConcordata[] falenciasConcordatasField;
        
        private ParticipacaoFalencia[] participacoesFalenciasField;
        
        private RestricaoFinanceira[] restricoesFinanceirasField;
        
        private Achei[] acheiRechequeField;
        
        private CCF[] bacenCCFField;
        
        private PendenciaFinanceira[] pendenciasFinanceirasField;
        
        private Convem[] convemDevedoresField;
        
        private Alerta[] alertasField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string SituacaoDocumento {
            get {
                return this.situacaoDocumentoField;
            }
            set {
                this.situacaoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        public string TotalOcorrencias {
            get {
                return this.totalOcorrenciasField;
            }
            set {
                this.totalOcorrenciasField = value;
            }
        }
        
        /// <remarks/>
        public Grafias[] Grafias {
            get {
                return this.grafiasField;
            }
            set {
                this.grafiasField = value;
            }
        }
        
        /// <remarks/>
        public Protesto[] Protestos {
            get {
                return this.protestosField;
            }
            set {
                this.protestosField = value;
            }
        }
        
        /// <remarks/>
        public AcaoJudicial[] AcoesJudiciais {
            get {
                return this.acoesJudiciaisField;
            }
            set {
                this.acoesJudiciaisField = value;
            }
        }
        
        /// <remarks/>
        public FalenciaConcordata[] FalenciasConcordatas {
            get {
                return this.falenciasConcordatasField;
            }
            set {
                this.falenciasConcordatasField = value;
            }
        }
        
        /// <remarks/>
        public ParticipacaoFalencia[] ParticipacoesFalencias {
            get {
                return this.participacoesFalenciasField;
            }
            set {
                this.participacoesFalenciasField = value;
            }
        }
        
        /// <remarks/>
        public RestricaoFinanceira[] RestricoesFinanceiras {
            get {
                return this.restricoesFinanceirasField;
            }
            set {
                this.restricoesFinanceirasField = value;
            }
        }
        
        /// <remarks/>
        public Achei[] AcheiRecheque {
            get {
                return this.acheiRechequeField;
            }
            set {
                this.acheiRechequeField = value;
            }
        }
        
        /// <remarks/>
        public CCF[] BacenCCF {
            get {
                return this.bacenCCFField;
            }
            set {
                this.bacenCCFField = value;
            }
        }
        
        /// <remarks/>
        public PendenciaFinanceira[] PendenciasFinanceiras {
            get {
                return this.pendenciasFinanceirasField;
            }
            set {
                this.pendenciasFinanceirasField = value;
            }
        }
        
        /// <remarks/>
        public Convem[] ConvemDevedores {
            get {
                return this.convemDevedoresField;
            }
            set {
                this.convemDevedoresField = value;
            }
        }
        
        /// <remarks/>
        public Alerta[] Alertas {
            get {
                return this.alertasField;
            }
            set {
                this.alertasField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ConcentreCompletedEventHandler(object sender, ConcentreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConcentreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConcentreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Concentre Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Concentre)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591