//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class ConfigPedidoBalcao : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigPedidoBalcao defaultInstance = ((ConfigPedidoBalcao)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigPedidoBalcao())));
        
        public static ConfigPedidoBalcao Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagPesquisaCodBarra {
            get {
                return ((string)(this["FlagPesquisaCodBarra"]));
            }
            set {
                this["FlagPesquisaCodBarra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagPesquisaCodReferencia {
            get {
                return ((string)(this["FlagPesquisaCodReferencia"]));
            }
            set {
                this["FlagPesquisaCodReferencia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AbreGaveta {
            get {
                return ((string)(this["AbreGaveta"]));
            }
            set {
                this["AbreGaveta"] = value;
            }
        }
    }
}
