//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class ConfigSistema1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigSistema1 defaultInstance = ((ConfigSistema1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigSistema1())));
        
        public static ConfigSistema1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\IMEXSISTEMA")]
        public string PathInstall {
            get {
                return ((string)(this["PathInstall"]));
            }
            set {
                this["PathInstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy/MM/dd")]
        public string FormatDateSearch {
            get {
                return ((string)(this["FormatDateSearch"]));
            }
            set {
                this["FormatDateSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorRequires {
            get {
                return ((global::System.Drawing.Color)(this["ColorRequires"]));
            }
            set {
                this["ColorRequires"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color ColorEnterTxtBox {
            get {
                return ((global::System.Drawing.Color)(this["ColorEnterTxtBox"]));
            }
            set {
                this["ColorEnterTxtBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User=SYSDBA;Password=masterkey;DataSource=localhost;Database=")]
        public string ConexaoFB {
            get {
                return ((string)(this["ConexaoFB"]));
            }
            set {
                this["ConexaoFB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 192, 255")]
        public string BackColorForm {
            get {
                return ((string)(this["BackColorForm"]));
            }
            set {
                this["BackColorForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MG")]
        public string UFSelect {
            get {
                return ((string)(this["UFSelect"]));
            }
            set {
                this["UFSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sistema de Gestão")]
        public string NameSytem {
            get {
                return ((string)(this["NameSytem"]));
            }
            set {
                this["NameSytem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\IMEXSISTEMA\\bd\\IMEXSISTEMAS.GDB;")]
        public string UrlBd {
            get {
                return ((string)(this["UrlBd"]));
            }
            set {
                this["UrlBd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorExitTxtBox {
            get {
                return ((global::System.Drawing.Color)(this["ColorExitTxtBox"]));
            }
            set {
                this["ColorExitTxtBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ColorFieldObs {
            get {
                return ((global::System.Drawing.Color)(this["ColorFieldObs"]));
            }
            set {
                this["ColorFieldObs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\IMEXSISTEMA\\Images")]
        public string PathImage {
            get {
                return ((string)(this["PathImage"]));
            }
            set {
                this["PathImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string CodMoedaSelec {
            get {
                return ((string)(this["CodMoedaSelec"]));
            }
            set {
                this["CodMoedaSelec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string FLAGPERGMODO {
            get {
                return ((string)(this["FLAGPERGMODO"]));
            }
            set {
                this["FLAGPERGMODO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string FLAGMODOGRAFICO {
            get {
                return ((string)(this["FLAGMODOGRAFICO"]));
            }
            set {
                this["FLAGMODOGRAFICO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string FLAGMODOMATRICIAL {
            get {
                return ((string)(this["FLAGMODOMATRICIAL"]));
            }
            set {
                this["FLAGMODOMATRICIAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string PORTAMATLOCAL {
            get {
                return ((string)(this["PORTAMATLOCAL"]));
            }
            set {
                this["PORTAMATLOCAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CAMINHOMATREDE {
            get {
                return ((string)(this["CAMINHOMATREDE"]));
            }
            set {
                this["CAMINHOMATREDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string FLAGMATRICIALLOCAL {
            get {
                return ((string)(this["FLAGMATRICIALLOCAL"]));
            }
            set {
                this["FLAGMATRICIALLOCAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string FLAGSOMLOCAL {
            get {
                return ((string)(this["FLAGSOMLOCAL"]));
            }
            set {
                this["FLAGSOMLOCAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string FLAGMATRICIALREDE {
            get {
                return ((string)(this["FLAGMATRICIALREDE"]));
            }
            set {
                this["FLAGMATRICIALREDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\IMEXSISTEMA\\backup")]
        public string PathBackup {
            get {
                return ((string)(this["PathBackup"]));
            }
            set {
                this["PathBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string FlackBancoBackup {
            get {
                return ((string)(this["FlackBancoBackup"]));
            }
            set {
                this["FlackBancoBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IMEXSISTEMAS.GDB")]
        public string NameBD {
            get {
                return ((string)(this["NameBD"]));
            }
            set {
                this["NameBD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\IMEXSISTEMA\\xmlnfe\\envio")]
        public string PathXmlEnvio {
            get {
                return ((string)(this["PathXmlEnvio"]));
            }
            set {
                this["PathXmlEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string impressoraticket {
            get {
                return ((string)(this["impressoraticket"]));
            }
            set {
                this["impressoraticket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string msg1ticket {
            get {
                return ((string)(this["msg1ticket"]));
            }
            set {
                this["msg1ticket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string msg2ticket {
            get {
                return ((string)(this["msg2ticket"]));
            }
            set {
                this["msg2ticket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string msg3ticket {
            get {
                return ((string)(this["msg3ticket"]));
            }
            set {
                this["msg3ticket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string msg4ticket {
            get {
                return ((string)(this["msg4ticket"]));
            }
            set {
                this["msg4ticket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imexsistema.com.br")]
        public string site {
            get {
                return ((string)(this["site"]));
            }
            set {
                this["site"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imexsistema@gmail.com")]
        public string email {
            get {
                return ((string)(this["email"]));
            }
            set {
                this["email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(31) 3611-4145")]
        public string telefone {
            get {
                return ((string)(this["telefone"]));
            }
            set {
                this["telefone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("001")]
        public string CodEmpresa {
            get {
                return ((string)(this["CodEmpresa"]));
            }
            set {
                this["CodEmpresa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TipoPesquisaProduto {
            get {
                return ((string)(this["TipoPesquisaProduto"]));
            }
            set {
                this["TipoPesquisaProduto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagExibirPedidoOptica {
            get {
                return ((string)(this["FlagExibirPedidoOptica"]));
            }
            set {
                this["FlagExibirPedidoOptica"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagExibirConhTransporte {
            get {
                return ((string)(this["FlagExibirConhTransporte"]));
            }
            set {
                this["FlagExibirConhTransporte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagAutoMecanica {
            get {
                return ((string)(this["FlagAutoMecanica"]));
            }
            set {
                this["FlagAutoMecanica"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagControlaEstoque {
            get {
                return ((string)(this["FlagControlaEstoque"]));
            }
            set {
                this["FlagControlaEstoque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TituloRelatorio {
            get {
                return ((string)(this["TituloRelatorio"]));
            }
            set {
                this["TituloRelatorio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagFestaEventos {
            get {
                return ((string)(this["FlagFestaEventos"]));
            }
            set {
                this["FlagFestaEventos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IMEX Sistemas")]
        public string NomeEmpresa {
            get {
                return ((string)(this["NomeEmpresa"]));
            }
            set {
                this["NomeEmpresa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagTerraplenagem {
            get {
                return ((string)(this["FlagTerraplenagem"]));
            }
            set {
                this["FlagTerraplenagem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public string PortaEmail {
            get {
                return ((string)(this["PortaEmail"]));
            }
            set {
                this["PortaEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string SegurancaEmail {
            get {
                return ((string)(this["SegurancaEmail"]));
            }
            set {
                this["SegurancaEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiferencaFuxoHorario {
            get {
                return ((string)(this["DiferencaFuxoHorario"]));
            }
            set {
                this["DiferencaFuxoHorario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagVendedorObrigatorio {
            get {
                return ((string)(this["FlagVendedorObrigatorio"]));
            }
            set {
                this["FlagVendedorObrigatorio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagCentroCustoObrigatorio {
            get {
                return ((string)(this["FlagCentroCustoObrigatorio"]));
            }
            set {
                this["FlagCentroCustoObrigatorio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagAdvogado {
            get {
                return ((string)(this["FlagAdvogado"]));
            }
            set {
                this["FlagAdvogado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usuarioserasa {
            get {
                return ((string)(this["usuarioserasa"]));
            }
            set {
                this["usuarioserasa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string senhaserasa {
            get {
                return ((string)(this["senhaserasa"]));
            }
            set {
                this["senhaserasa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string FlagPlanos {
            get {
                return ((string)(this["FlagPlanos"]));
            }
            set {
                this["FlagPlanos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string IdPlanos {
            get {
                return ((string)(this["IdPlanos"]));
            }
            set {
                this["IdPlanos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagOrdenarProdutoPedido {
            get {
                return ((string)(this["FlagOrdenarProdutoPedido"]));
            }
            set {
                this["FlagOrdenarProdutoPedido"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagClienteResumida {
            get {
                return ((string)(this["FlagClienteResumida"]));
            }
            set {
                this["FlagClienteResumida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagProdutoResumida {
            get {
                return ((string)(this["FlagProdutoResumida"]));
            }
            set {
                this["FlagProdutoResumida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\IMEXSISTEMA\\BD\\SCRIPTBDIMEX.GDB")]
        public string BDScript {
            get {
                return ((string)(this["BDScript"]));
            }
            set {
                this["BDScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UploadSicron {
            get {
                return ((string)(this["UploadSicron"]));
            }
            set {
                this["UploadSicron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadSicron {
            get {
                return ((string)(this["DownloadSicron"]));
            }
            set {
                this["DownloadSicron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagMetroLinear {
            get {
                return ((string)(this["FlagMetroLinear"]));
            }
            set {
                this["FlagMetroLinear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagAluguelRoupa {
            get {
                return ((string)(this["FlagAluguelRoupa"]));
            }
            set {
                this["FlagAluguelRoupa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string IntResolucao {
            get {
                return ((string)(this["IntResolucao"]));
            }
            set {
                this["IntResolucao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagTelemarketing {
            get {
                return ((string)(this["FlagTelemarketing"]));
            }
            set {
                this["FlagTelemarketing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagEmissorNFe {
            get {
                return ((string)(this["FlagEmissorNFe"]));
            }
            set {
                this["FlagEmissorNFe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagSpedSintegra {
            get {
                return ((string)(this["FlagSpedSintegra"]));
            }
            set {
                this["FlagSpedSintegra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagContadorNFe {
            get {
                return ((string)(this["FlagContadorNFe"]));
            }
            set {
                this["FlagContadorNFe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagMsgSuporte {
            get {
                return ((string)(this["FlagMsgSuporte"]));
            }
            set {
                this["FlagMsgSuporte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagExibirMsgRenovacaoSuporte {
            get {
                return ((string)(this["FlagExibirMsgRenovacaoSuporte"]));
            }
            set {
                this["FlagExibirMsgRenovacaoSuporte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DtSuporte {
            get {
                return ((string)(this["DtSuporte"]));
            }
            set {
                this["DtSuporte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColunaArquivoRemessa {
            get {
                return ((string)(this["ColunaArquivoRemessa"]));
            }
            set {
                this["ColunaArquivoRemessa"] = value;
            }
        }
    }
}
