//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ConfigNotaFiscalServico : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigNotaFiscalServico defaultInstance = ((ConfigNotaFiscalServico)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigNotaFiscalServico())));
        
        public static ConfigNotaFiscalServico Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CodNatureza {
            get {
                return ((string)(this["CodNatureza"]));
            }
            set {
                this["CodNatureza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegimeTributacao {
            get {
                return ((string)(this["RegimeTributacao"]));
            }
            set {
                this["RegimeTributacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Serie {
            get {
                return ((string)(this["Serie"]));
            }
            set {
                this["Serie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InscricaoMunicipalPrestador {
            get {
                return ((string)(this["InscricaoMunicipalPrestador"]));
            }
            set {
                this["InscricaoMunicipalPrestador"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptanteSimples {
            get {
                return ((string)(this["OptanteSimples"]));
            }
            set {
                this["OptanteSimples"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalArquivoTexto {
            get {
                return ((string)(this["LocalArquivoTexto"]));
            }
            set {
                this["LocalArquivoTexto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CodigoEspecificaçãoAtividadeFederal {
            get {
                return ((string)(this["CodigoEspecificaçãoAtividadeFederal"]));
            }
            set {
                this["CodigoEspecificaçãoAtividadeFederal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CodigoEspecificacaoAtividadeMunicipal {
            get {
                return ((string)(this["CodigoEspecificacaoAtividadeMunicipal"]));
            }
            set {
                this["CodigoEspecificacaoAtividadeMunicipal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Aliquota {
            get {
                return ((string)(this["Aliquota"]));
            }
            set {
                this["Aliquota"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InscricaoEstadualPrestador {
            get {
                return ((string)(this["InscricaoEstadualPrestador"]));
            }
            set {
                this["InscricaoEstadualPrestador"] = value;
            }
        }
    }
}
