//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class ConfigEtiqueta : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigEtiqueta defaultInstance = ((ConfigEtiqueta)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigEtiqueta())));
        
        public static ConfigEtiqueta Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string Left_Esquerda_POLIFIX_2060 {
            get {
                return ((string)(this["Left_Esquerda_POLIFIX_2060"]));
            }
            set {
                this["Left_Esquerda_POLIFIX_2060"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string Right_Direito_POLIFIX_2060 {
            get {
                return ((string)(this["Right_Direito_POLIFIX_2060"]));
            }
            set {
                this["Right_Direito_POLIFIX_2060"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string Top_Topo_POLIFIX_2060 {
            get {
                return ((string)(this["Top_Topo_POLIFIX_2060"]));
            }
            set {
                this["Top_Topo_POLIFIX_2060"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string Bottom_Inferior_POLIFIX_2060 {
            get {
                return ((string)(this["Bottom_Inferior_POLIFIX_2060"]));
            }
            set {
                this["Bottom_Inferior_POLIFIX_2060"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public string Width_Largura_POLIFIX_2060 {
            get {
                return ((string)(this["Width_Largura_POLIFIX_2060"]));
            }
            set {
                this["Width_Largura_POLIFIX_2060"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public string Height_Altura_POLIFIX_2060 {
            get {
                return ((string)(this["Height_Altura_POLIFIX_2060"]));
            }
            set {
                this["Height_Altura_POLIFIX_2060"] = value;
            }
        }
    }
}
