//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ConfigOS : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigOS defaultInstance = ((ConfigOS)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigOS())));
        
        public static ConfigOS Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModeloImpressao {
            get {
                return ((string)(this["ModeloImpressao"]));
            }
            set {
                this["ModeloImpressao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagPrintDireto {
            get {
                return ((string)(this["FlagPrintDireto"]));
            }
            set {
                this["FlagPrintDireto"] = value;
            }
        }
    }
}
