//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ConfigMessage : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigMessage defaultInstance = ((ConfigMessage)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigMessage())));
        
        public static ConfigMessage Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Registro salvo com sucesso!")]
        public string MsgSave {
            get {
                return ((string)(this["MsgSave"]));
            }
            set {
                this["MsgSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Não foi possível salvar o registro!")]
        public string MsgSaveErro {
            get {
                return ((string)(this["MsgSaveErro"]));
            }
            set {
                this["MsgSaveErro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CPF Inválido!")]
        public string CPFErro {
            get {
                return ((string)(this["CPFErro"]));
            }
            set {
                this["CPFErro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNPJ Inválido!")]
        public string CNPJErro {
            get {
                return ((string)(this["CNPJErro"]));
            }
            set {
                this["CNPJErro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Campo obrigatório")]
        public string CampoObrigatorio {
            get {
                return ((string)(this["CampoObrigatorio"]));
            }
            set {
                this["CampoObrigatorio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Existe(m) campo(s) obrigatório(s)")]
        public string CampoObrigatorio2 {
            get {
                return ((string)(this["CampoObrigatorio2"]));
            }
            set {
                this["CampoObrigatorio2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Erro no valor da pesquisa")]
        public string searchFieldType {
            get {
                return ((string)(this["searchFieldType"]));
            }
            set {
                this["searchFieldType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Desejar realmente excluir este registro?")]
        public string MsgDelete {
            get {
                return ((string)(this["MsgDelete"]));
            }
            set {
                this["MsgDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selecione um registro!")]
        public string MsgSelecRegistro {
            get {
                return ((string)(this["MsgSelecRegistro"]));
            }
            set {
                this["MsgSelecRegistro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Registro deletado com sucesso!")]
        public string MsgDelete2 {
            get {
                return ((string)(this["MsgDelete2"]));
            }
            set {
                this["MsgDelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Não foi possível deletar o registro selecionado!")]
        public string MsgDeleteErro {
            get {
                return ((string)(this["MsgDeleteErro"]));
            }
            set {
                this["MsgDeleteErro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNPJ já existe no cadastro, desejar continuar?")]
        public string CNPJDupl {
            get {
                return ((string)(this["CNPJDupl"]));
            }
            set {
                this["CNPJDupl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Não foi possível imprimir!")]
        public string MsgErroPrint {
            get {
                return ((string)(this["MsgErroPrint"]));
            }
            set {
                this["MsgErroPrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CPF já existe no cadastro, desejar continuar?")]
        public string CPFDupl {
            get {
                return ((string)(this["CPFDupl"]));
            }
            set {
                this["CPFDupl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Inválida!")]
        public string MsgDataInvalida {
            get {
                return ((string)(this["MsgDataInvalida"]));
            }
            set {
                this["MsgDataInvalida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Campo inválido!")]
        public string FieldErro {
            get {
                return ((string)(this["FieldErro"]));
            }
            set {
                this["FieldErro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Selecione...")]
        public string MsgDrop {
            get {
                return ((string)(this["MsgDrop"]));
            }
            set {
                this["MsgDrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNPJ e/ou CPF já existe no cadastro, deseja continuar?")]
        public string CNPJCPFDupl {
            get {
                return ((string)(this["CNPJCPFDupl"]));
            }
            set {
                this["CNPJCPFDupl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Não foi possível visualizar o arquivo!")]
        public string MsgErroArquivo {
            get {
                return ((string)(this["MsgErroArquivo"]));
            }
            set {
                this["MsgErroArquivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Não foi possível pesquisar pelo código selecionado!")]
        public string MsgSearchErro {
            get {
                return ((string)(this["MsgSearchErro"]));
            }
            set {
                this["MsgSearchErro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pesquisa realizada com sucesso!")]
        public string MsgSearchSucess {
            get {
                return ((string)(this["MsgSearchSucess"]));
            }
            set {
                this["MsgSearchSucess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Senha/Usuário inválido!")]
        public string MsgErroSenha {
            get {
                return ((string)(this["MsgErroSenha"]));
            }
            set {
                this["MsgErroSenha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Não foi possível abrir o registro!")]
        public string MsgErroOpenRegistro {
            get {
                return ((string)(this["MsgErroOpenRegistro"]));
            }
            set {
                this["MsgErroOpenRegistro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Faça a pesquisa antes de imprimir!")]
        public string MsgErroImprimirPesquisa {
            get {
                return ((string)(this["MsgErroImprimirPesquisa"]));
            }
            set {
                this["MsgErroImprimirPesquisa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Não existe boleta bancária selecionada na configuração.")]
        public string MsgErroBoletaSelec {
            get {
                return ((string)(this["MsgErroBoletaSelec"]));
            }
            set {
                this["MsgErroBoletaSelec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Para editar o registro pressione Enter ou Delete para apagar.")]
        public string MsgEditarExcluir {
            get {
                return ((string)(this["MsgEditarExcluir"]));
            }
            set {
                this["MsgEditarExcluir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hora inválida")]
        public string MsgErroHora {
            get {
                return ((string)(this["MsgErroHora"]));
            }
            set {
                this["MsgErroHora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Deseja Realmente duplicar o Registro?")]
        public string MsgDuplRegistro {
            get {
                return ((string)(this["MsgDuplRegistro"]));
            }
            set {
                this["MsgDuplRegistro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Não foi possível efetuar a pesquisa!")]
        public string MsgErroPesquisa {
            get {
                return ((string)(this["MsgErroPesquisa"]));
            }
            set {
                this["MsgErroPesquisa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuário não tem permissão para usar este recurso!")]
        public string MsgPerm {
            get {
                return ((string)(this["MsgPerm"]));
            }
            set {
                this["MsgPerm"] = value;
            }
        }
    }
}
