//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class ConfigOS : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigOS defaultInstance = ((ConfigOS)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigOS())));
        
        public static ConfigOS Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModeloImpressao {
            get {
                return ((string)(this["ModeloImpressao"]));
            }
            set {
                this["ModeloImpressao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlagPrintDireto {
            get {
                return ((string)(this["FlagPrintDireto"]));
            }
            set {
                this["FlagPrintDireto"] = value;
            }
        }
    }
}
