//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class CupomFiscal : global::System.Configuration.ApplicationSettingsBase {
        
        private static CupomFiscal defaultInstance = ((CupomFiscal)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CupomFiscal())));
        
        public static CupomFiscal Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pathgdoor {
            get {
                return ((string)(this["pathgdoor"]));
            }
            set {
                this["pathgdoor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bdgoor {
            get {
                return ((string)(this["bdgoor"]));
            }
            set {
                this["bdgoor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bdFast {
            get {
                return ((string)(this["bdFast"]));
            }
            set {
                this["bdFast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pathfast {
            get {
                return ((string)(this["pathfast"]));
            }
            set {
                this["pathfast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PATHRECEPDIGISAT {
            get {
                return ((string)(this["PATHRECEPDIGISAT"]));
            }
            set {
                this["PATHRECEPDIGISAT"] = value;
            }
        }
    }
}
