//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class WebServiceNfe : global::System.Configuration.ApplicationSettingsBase {
        
        private static WebServiceNfe defaultInstance = ((WebServiceNfe)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WebServiceNfe())));
        
        public static WebServiceNfe Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Recepcao {
            get {
                return ((string)(this["Recepcao"]));
            }
            set {
                this["Recepcao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RetRecepcao {
            get {
                return ((string)(this["RetRecepcao"]));
            }
            set {
                this["RetRecepcao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Inutilizacao {
            get {
                return ((string)(this["Inutilizacao"]));
            }
            set {
                this["Inutilizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConsultaProtocolo {
            get {
                return ((string)(this["ConsultaProtocolo"]));
            }
            set {
                this["ConsultaProtocolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StatusServico {
            get {
                return ((string)(this["StatusServico"]));
            }
            set {
                this["StatusServico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConsultaCadastro {
            get {
                return ((string)(this["ConsultaCadastro"]));
            }
            set {
                this["ConsultaCadastro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecepcaoEvento {
            get {
                return ((string)(this["RecepcaoEvento"]));
            }
            set {
                this["RecepcaoEvento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Autorizacao {
            get {
                return ((string)(this["Autorizacao"]));
            }
            set {
                this["Autorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RetAutorizacao {
            get {
                return ((string)(this["RetAutorizacao"]));
            }
            set {
                this["RetAutorizacao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DownloadNFe {
            get {
                return ((string)(this["DownloadNFe"]));
            }
            set {
                this["DownloadNFe"] = value;
            }
        }
    }
}
