//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BmsSoftware.Serasa.administracao {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdministracaoSoap", Namespace="SOAWebServices")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Serialization))]
    public partial class Administracao : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatusServicosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExtratoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExtratoAnaliticoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExtratoAnaliticoPorDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback HistoricoDetalhadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Administracao() {
            this.Url = global::BmsSoftware.Properties.Settings.Default.IMEXSistema_Serasa_administracao_Administracao;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaldoCompletedEventHandler SaldoCompleted;
        
        /// <remarks/>
        public event StatusServicosCompletedEventHandler StatusServicosCompleted;
        
        /// <remarks/>
        public event ExtratoCompletedEventHandler ExtratoCompleted;
        
        /// <remarks/>
        public event ExtratoAnaliticoCompletedEventHandler ExtratoAnaliticoCompleted;
        
        /// <remarks/>
        public event ExtratoAnaliticoPorDocumentoCompletedEventHandler ExtratoAnaliticoPorDocumentoCompleted;
        
        /// <remarks/>
        public event HistoricoDetalhadoCompletedEventHandler HistoricoDetalhadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/Saldo", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Saldo Saldo(Credenciais Credenciais) {
            object[] results = this.Invoke("Saldo", new object[] {
                        Credenciais});
            return ((Saldo)(results[0]));
        }
        
        /// <remarks/>
        public void SaldoAsync(Credenciais Credenciais) {
            this.SaldoAsync(Credenciais, null);
        }
        
        /// <remarks/>
        public void SaldoAsync(Credenciais Credenciais, object userState) {
            if ((this.SaldoOperationCompleted == null)) {
                this.SaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaldoOperationCompleted);
            }
            this.InvokeAsync("Saldo", new object[] {
                        Credenciais}, this.SaldoOperationCompleted, userState);
        }
        
        private void OnSaldoOperationCompleted(object arg) {
            if ((this.SaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaldoCompleted(this, new SaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/StatusServicos", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StatusServicos StatusServicos(Credenciais Credenciais) {
            object[] results = this.Invoke("StatusServicos", new object[] {
                        Credenciais});
            return ((StatusServicos)(results[0]));
        }
        
        /// <remarks/>
        public void StatusServicosAsync(Credenciais Credenciais) {
            this.StatusServicosAsync(Credenciais, null);
        }
        
        /// <remarks/>
        public void StatusServicosAsync(Credenciais Credenciais, object userState) {
            if ((this.StatusServicosOperationCompleted == null)) {
                this.StatusServicosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatusServicosOperationCompleted);
            }
            this.InvokeAsync("StatusServicos", new object[] {
                        Credenciais}, this.StatusServicosOperationCompleted, userState);
        }
        
        private void OnStatusServicosOperationCompleted(object arg) {
            if ((this.StatusServicosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatusServicosCompleted(this, new StatusServicosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/Extrato", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Extrato Extrato(Credenciais Credenciais, string Mes, string Ano) {
            object[] results = this.Invoke("Extrato", new object[] {
                        Credenciais,
                        Mes,
                        Ano});
            return ((Extrato)(results[0]));
        }
        
        /// <remarks/>
        public void ExtratoAsync(Credenciais Credenciais, string Mes, string Ano) {
            this.ExtratoAsync(Credenciais, Mes, Ano, null);
        }
        
        /// <remarks/>
        public void ExtratoAsync(Credenciais Credenciais, string Mes, string Ano, object userState) {
            if ((this.ExtratoOperationCompleted == null)) {
                this.ExtratoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtratoOperationCompleted);
            }
            this.InvokeAsync("Extrato", new object[] {
                        Credenciais,
                        Mes,
                        Ano}, this.ExtratoOperationCompleted, userState);
        }
        
        private void OnExtratoOperationCompleted(object arg) {
            if ((this.ExtratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExtratoCompleted(this, new ExtratoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/ExtratoAnalitico", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExtratoAnalitico ExtratoAnalitico(Credenciais Credenciais, string Mes, string Ano) {
            object[] results = this.Invoke("ExtratoAnalitico", new object[] {
                        Credenciais,
                        Mes,
                        Ano});
            return ((ExtratoAnalitico)(results[0]));
        }
        
        /// <remarks/>
        public void ExtratoAnaliticoAsync(Credenciais Credenciais, string Mes, string Ano) {
            this.ExtratoAnaliticoAsync(Credenciais, Mes, Ano, null);
        }
        
        /// <remarks/>
        public void ExtratoAnaliticoAsync(Credenciais Credenciais, string Mes, string Ano, object userState) {
            if ((this.ExtratoAnaliticoOperationCompleted == null)) {
                this.ExtratoAnaliticoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtratoAnaliticoOperationCompleted);
            }
            this.InvokeAsync("ExtratoAnalitico", new object[] {
                        Credenciais,
                        Mes,
                        Ano}, this.ExtratoAnaliticoOperationCompleted, userState);
        }
        
        private void OnExtratoAnaliticoOperationCompleted(object arg) {
            if ((this.ExtratoAnaliticoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExtratoAnaliticoCompleted(this, new ExtratoAnaliticoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/ExtratoAnaliticoPorDocumento", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExtratoAnalitico ExtratoAnaliticoPorDocumento(Credenciais Credenciais, string Documento) {
            object[] results = this.Invoke("ExtratoAnaliticoPorDocumento", new object[] {
                        Credenciais,
                        Documento});
            return ((ExtratoAnalitico)(results[0]));
        }
        
        /// <remarks/>
        public void ExtratoAnaliticoPorDocumentoAsync(Credenciais Credenciais, string Documento) {
            this.ExtratoAnaliticoPorDocumentoAsync(Credenciais, Documento, null);
        }
        
        /// <remarks/>
        public void ExtratoAnaliticoPorDocumentoAsync(Credenciais Credenciais, string Documento, object userState) {
            if ((this.ExtratoAnaliticoPorDocumentoOperationCompleted == null)) {
                this.ExtratoAnaliticoPorDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExtratoAnaliticoPorDocumentoOperationCompleted);
            }
            this.InvokeAsync("ExtratoAnaliticoPorDocumento", new object[] {
                        Credenciais,
                        Documento}, this.ExtratoAnaliticoPorDocumentoOperationCompleted, userState);
        }
        
        private void OnExtratoAnaliticoPorDocumentoOperationCompleted(object arg) {
            if ((this.ExtratoAnaliticoPorDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExtratoAnaliticoPorDocumentoCompleted(this, new ExtratoAnaliticoPorDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("SOAWebServices/HistoricoDetalhado", RequestNamespace="SOAWebServices", ResponseNamespace="SOAWebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HistoricoDetalhado HistoricoDetalhado(Credenciais Credenciais, string UniqueID) {
            object[] results = this.Invoke("HistoricoDetalhado", new object[] {
                        Credenciais,
                        UniqueID});
            return ((HistoricoDetalhado)(results[0]));
        }
        
        /// <remarks/>
        public void HistoricoDetalhadoAsync(Credenciais Credenciais, string UniqueID) {
            this.HistoricoDetalhadoAsync(Credenciais, UniqueID, null);
        }
        
        /// <remarks/>
        public void HistoricoDetalhadoAsync(Credenciais Credenciais, string UniqueID, object userState) {
            if ((this.HistoricoDetalhadoOperationCompleted == null)) {
                this.HistoricoDetalhadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHistoricoDetalhadoOperationCompleted);
            }
            this.InvokeAsync("HistoricoDetalhado", new object[] {
                        Credenciais,
                        UniqueID}, this.HistoricoDetalhadoOperationCompleted, userState);
        }
        
        private void OnHistoricoDetalhadoOperationCompleted(object arg) {
            if ((this.HistoricoDetalhadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HistoricoDetalhadoCompleted(this, new HistoricoDetalhadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Credenciais {
        
        private string emailField;
        
        private string senhaField;
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class HistoricoDetalhado {
        
        private string documentoField;
        
        private string produtoField;
        
        private string conteudoXMLField;
        
        private string valorField;
        
        private System.DateTime datahoraField;
        
        private string iPAddressField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        public string ConteudoXML {
            get {
                return this.conteudoXMLField;
            }
            set {
                this.conteudoXMLField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Datahora {
            get {
                return this.datahoraField;
            }
            set {
                this.datahoraField = value;
            }
        }
        
        /// <remarks/>
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Historico {
        
        private string uniqueIDField;
        
        private string documentoField;
        
        private string valorField;
        
        private System.DateTime datahoraField;
        
        private string iPAddressField;
        
        /// <remarks/>
        public string UniqueID {
            get {
                return this.uniqueIDField;
            }
            set {
                this.uniqueIDField = value;
            }
        }
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Datahora {
            get {
                return this.datahoraField;
            }
            set {
                this.datahoraField = value;
            }
        }
        
        /// <remarks/>
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Servico {
        
        private string nomeField;
        
        private string performanceField;
        
        private TipoStatus statusField;
        
        private System.DateTime dataHoraField;
        
        private bool suspensoField;
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Performance {
            get {
                return this.performanceField;
            }
            set {
                this.performanceField = value;
            }
        }
        
        /// <remarks/>
        public TipoStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataHora {
            get {
                return this.dataHoraField;
            }
            set {
                this.dataHoraField = value;
            }
        }
        
        /// <remarks/>
        public bool Suspenso {
            get {
                return this.suspensoField;
            }
            set {
                this.suspensoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public enum TipoStatus {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        FAILURE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Regiao {
        
        private int idField;
        
        private string nomeField;
        
        private Servico[] servicosField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public Servico[] Servicos {
            get {
                return this.servicosField;
            }
            set {
                this.servicosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtratoAnalitico))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Produto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Extrato))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusServicos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Saldo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Serialization {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class ExtratoAnalitico : Serialization {
        
        private Historico[] historicosField;
        
        private int totalConsultasField;
        
        private string valorTotalField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public Historico[] Historicos {
            get {
                return this.historicosField;
            }
            set {
                this.historicosField = value;
            }
        }
        
        /// <remarks/>
        public int TotalConsultas {
            get {
                return this.totalConsultasField;
            }
            set {
                this.totalConsultasField = value;
            }
        }
        
        /// <remarks/>
        public string ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Produto : Serialization {
        
        private string produto1Field;
        
        private string mesField;
        
        private string anoField;
        
        private int quantidadeField;
        
        private decimal consumoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Produto")]
        public string Produto1 {
            get {
                return this.produto1Field;
            }
            set {
                this.produto1Field = value;
            }
        }
        
        /// <remarks/>
        public string Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        public string Ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Consumo {
            get {
                return this.consumoField;
            }
            set {
                this.consumoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Extrato : Serialization {
        
        private Produto[] produtosField;
        
        private decimal saldoField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public Produto[] Produtos {
            get {
                return this.produtosField;
            }
            set {
                this.produtosField = value;
            }
        }
        
        /// <remarks/>
        public decimal Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class StatusServicos : Serialization {
        
        private Regiao[] regioesField;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        public Regiao[] Regioes {
            get {
                return this.regioesField;
            }
            set {
                this.regioesField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="SOAWebServices")]
    public partial class Saldo : Serialization {
        
        private decimal saldo1Field;
        
        private string mensagemField;
        
        private bool statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Saldo")]
        public decimal Saldo1 {
            get {
                return this.saldo1Field;
            }
            set {
                this.saldo1Field = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaldoCompletedEventHandler(object sender, SaldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Saldo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Saldo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void StatusServicosCompletedEventHandler(object sender, StatusServicosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatusServicosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatusServicosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StatusServicos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StatusServicos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ExtratoCompletedEventHandler(object sender, ExtratoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtratoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExtratoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Extrato Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Extrato)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ExtratoAnaliticoCompletedEventHandler(object sender, ExtratoAnaliticoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtratoAnaliticoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExtratoAnaliticoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtratoAnalitico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtratoAnalitico)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ExtratoAnaliticoPorDocumentoCompletedEventHandler(object sender, ExtratoAnaliticoPorDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtratoAnaliticoPorDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExtratoAnaliticoPorDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtratoAnalitico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtratoAnalitico)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void HistoricoDetalhadoCompletedEventHandler(object sender, HistoricoDetalhadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HistoricoDetalhadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HistoricoDetalhadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HistoricoDetalhado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HistoricoDetalhado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591