//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace BmsSoftware.NFCeServiceClient {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_NFCeService", Namespace="http://tempuri.org/")]
    public partial class NFCeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutorizaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InutilizaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusPorChaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatusPorOidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUrlConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUrlQrCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQrCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProtocoloAutorizacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrototoloCancelamentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NFCeService() {
            this.Url = global::BmsSoftware.Properties.Settings.Default.BmsSoftware_NFCeServiceClient_NFCeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event AutorizaCompletedEventHandler AutorizaCompleted;
        
        /// <remarks/>
        public event CancelaCompletedEventHandler CancelaCompleted;
        
        /// <remarks/>
        public event InutilizaCompletedEventHandler InutilizaCompleted;
        
        /// <remarks/>
        public event GetStatusPorChaveCompletedEventHandler GetStatusPorChaveCompleted;
        
        /// <remarks/>
        public event GetStatusPorOidCompletedEventHandler GetStatusPorOidCompleted;
        
        /// <remarks/>
        public event GetDocCompletedEventHandler GetDocCompleted;
        
        /// <remarks/>
        public event GetUrlConsultaCompletedEventHandler GetUrlConsultaCompleted;
        
        /// <remarks/>
        public event GetUrlQrCodeCompletedEventHandler GetUrlQrCodeCompleted;
        
        /// <remarks/>
        public event GetQrCodeCompletedEventHandler GetQrCodeCompleted;
        
        /// <remarks/>
        public event GetProtocoloAutorizacaoCompletedEventHandler GetProtocoloAutorizacaoCompleted;
        
        /// <remarks/>
        public event GetPrototoloCancelamentoCompletedEventHandler GetPrototoloCancelamentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/Ping", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Ping() {
            this.Invoke("Ping", new object[0]);
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/Autoriza", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public retStatus Autoriza([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("Autoriza", new object[] {
                        cnpj,
                        xml});
            return ((retStatus)(results[0]));
        }
        
        /// <remarks/>
        public void AutorizaAsync(string cnpj, string xml) {
            this.AutorizaAsync(cnpj, xml, null);
        }
        
        /// <remarks/>
        public void AutorizaAsync(string cnpj, string xml, object userState) {
            if ((this.AutorizaOperationCompleted == null)) {
                this.AutorizaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutorizaOperationCompleted);
            }
            this.InvokeAsync("Autoriza", new object[] {
                        cnpj,
                        xml}, this.AutorizaOperationCompleted, userState);
        }
        
        private void OnAutorizaOperationCompleted(object arg) {
            if ((this.AutorizaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutorizaCompleted(this, new AutorizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/Cancela", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public retStatus Cancela([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string chave, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string justificativa) {
            object[] results = this.Invoke("Cancela", new object[] {
                        cnpj,
                        chave,
                        justificativa});
            return ((retStatus)(results[0]));
        }
        
        /// <remarks/>
        public void CancelaAsync(string cnpj, string chave, string justificativa) {
            this.CancelaAsync(cnpj, chave, justificativa, null);
        }
        
        /// <remarks/>
        public void CancelaAsync(string cnpj, string chave, string justificativa, object userState) {
            if ((this.CancelaOperationCompleted == null)) {
                this.CancelaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelaOperationCompleted);
            }
            this.InvokeAsync("Cancela", new object[] {
                        cnpj,
                        chave,
                        justificativa}, this.CancelaOperationCompleted, userState);
        }
        
        private void OnCancelaOperationCompleted(object arg) {
            if ((this.CancelaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelaCompleted(this, new CancelaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/Inutiliza", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Inutiliza([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> serie, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool serieSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> numero, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool numeroSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string justificativa, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string detalhes) {
            object[] results = this.Invoke("Inutiliza", new object[] {
                        cnpj,
                        serie,
                        serieSpecified,
                        numero,
                        numeroSpecified,
                        justificativa});
            detalhes = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InutilizaAsync(string cnpj, System.Nullable<int> serie, bool serieSpecified, System.Nullable<int> numero, bool numeroSpecified, string justificativa) {
            this.InutilizaAsync(cnpj, serie, serieSpecified, numero, numeroSpecified, justificativa, null);
        }
        
        /// <remarks/>
        public void InutilizaAsync(string cnpj, System.Nullable<int> serie, bool serieSpecified, System.Nullable<int> numero, bool numeroSpecified, string justificativa, object userState) {
            if ((this.InutilizaOperationCompleted == null)) {
                this.InutilizaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInutilizaOperationCompleted);
            }
            this.InvokeAsync("Inutiliza", new object[] {
                        cnpj,
                        serie,
                        serieSpecified,
                        numero,
                        numeroSpecified,
                        justificativa}, this.InutilizaOperationCompleted, userState);
        }
        
        private void OnInutilizaOperationCompleted(object arg) {
            if ((this.InutilizaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InutilizaCompleted(this, new InutilizaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/GetStatusPorChave", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public retStatus GetStatusPorChave([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string chave) {
            object[] results = this.Invoke("GetStatusPorChave", new object[] {
                        cnpj,
                        chave});
            return ((retStatus)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusPorChaveAsync(string cnpj, string chave) {
            this.GetStatusPorChaveAsync(cnpj, chave, null);
        }
        
        /// <remarks/>
        public void GetStatusPorChaveAsync(string cnpj, string chave, object userState) {
            if ((this.GetStatusPorChaveOperationCompleted == null)) {
                this.GetStatusPorChaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusPorChaveOperationCompleted);
            }
            this.InvokeAsync("GetStatusPorChave", new object[] {
                        cnpj,
                        chave}, this.GetStatusPorChaveOperationCompleted, userState);
        }
        
        private void OnGetStatusPorChaveOperationCompleted(object arg) {
            if ((this.GetStatusPorChaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusPorChaveCompleted(this, new GetStatusPorChaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/GetStatusPorOid", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public retStatus GetStatusPorOid([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> oid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool oidSpecified) {
            object[] results = this.Invoke("GetStatusPorOid", new object[] {
                        cnpj,
                        oid,
                        oidSpecified});
            return ((retStatus)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatusPorOidAsync(string cnpj, System.Nullable<int> oid, bool oidSpecified) {
            this.GetStatusPorOidAsync(cnpj, oid, oidSpecified, null);
        }
        
        /// <remarks/>
        public void GetStatusPorOidAsync(string cnpj, System.Nullable<int> oid, bool oidSpecified, object userState) {
            if ((this.GetStatusPorOidOperationCompleted == null)) {
                this.GetStatusPorOidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatusPorOidOperationCompleted);
            }
            this.InvokeAsync("GetStatusPorOid", new object[] {
                        cnpj,
                        oid,
                        oidSpecified}, this.GetStatusPorOidOperationCompleted, userState);
        }
        
        private void OnGetStatusPorOidOperationCompleted(object arg) {
            if ((this.GetStatusPorOidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatusPorOidCompleted(this, new GetStatusPorOidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/GetDoc", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDoc([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string chave) {
            object[] results = this.Invoke("GetDoc", new object[] {
                        cnpj,
                        chave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDocAsync(string cnpj, string chave) {
            this.GetDocAsync(cnpj, chave, null);
        }
        
        /// <remarks/>
        public void GetDocAsync(string cnpj, string chave, object userState) {
            if ((this.GetDocOperationCompleted == null)) {
                this.GetDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDocOperationCompleted);
            }
            this.InvokeAsync("GetDoc", new object[] {
                        cnpj,
                        chave}, this.GetDocOperationCompleted, userState);
        }
        
        private void OnGetDocOperationCompleted(object arg) {
            if ((this.GetDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDocCompleted(this, new GetDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/GetUrlConsulta", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetUrlConsulta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj) {
            object[] results = this.Invoke("GetUrlConsulta", new object[] {
                        cnpj});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUrlConsultaAsync(string cnpj) {
            this.GetUrlConsultaAsync(cnpj, null);
        }
        
        /// <remarks/>
        public void GetUrlConsultaAsync(string cnpj, object userState) {
            if ((this.GetUrlConsultaOperationCompleted == null)) {
                this.GetUrlConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUrlConsultaOperationCompleted);
            }
            this.InvokeAsync("GetUrlConsulta", new object[] {
                        cnpj}, this.GetUrlConsultaOperationCompleted, userState);
        }
        
        private void OnGetUrlConsultaOperationCompleted(object arg) {
            if ((this.GetUrlConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUrlConsultaCompleted(this, new GetUrlConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/GetUrlQrCode", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetUrlQrCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string chave) {
            object[] results = this.Invoke("GetUrlQrCode", new object[] {
                        cnpj,
                        chave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUrlQrCodeAsync(string cnpj, string chave) {
            this.GetUrlQrCodeAsync(cnpj, chave, null);
        }
        
        /// <remarks/>
        public void GetUrlQrCodeAsync(string cnpj, string chave, object userState) {
            if ((this.GetUrlQrCodeOperationCompleted == null)) {
                this.GetUrlQrCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUrlQrCodeOperationCompleted);
            }
            this.InvokeAsync("GetUrlQrCode", new object[] {
                        cnpj,
                        chave}, this.GetUrlQrCodeOperationCompleted, userState);
        }
        
        private void OnGetUrlQrCodeOperationCompleted(object arg) {
            if ((this.GetUrlQrCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUrlQrCodeCompleted(this, new GetUrlQrCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/GetQrCode", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] GetQrCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string chave) {
            object[] results = this.Invoke("GetQrCode", new object[] {
                        cnpj,
                        chave});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetQrCodeAsync(string cnpj, string chave) {
            this.GetQrCodeAsync(cnpj, chave, null);
        }
        
        /// <remarks/>
        public void GetQrCodeAsync(string cnpj, string chave, object userState) {
            if ((this.GetQrCodeOperationCompleted == null)) {
                this.GetQrCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQrCodeOperationCompleted);
            }
            this.InvokeAsync("GetQrCode", new object[] {
                        cnpj,
                        chave}, this.GetQrCodeOperationCompleted, userState);
        }
        
        private void OnGetQrCodeOperationCompleted(object arg) {
            if ((this.GetQrCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQrCodeCompleted(this, new GetQrCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/GetProtocoloAutorizacao", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetProtocoloAutorizacao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string chave) {
            object[] results = this.Invoke("GetProtocoloAutorizacao", new object[] {
                        cnpj,
                        chave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProtocoloAutorizacaoAsync(string cnpj, string chave) {
            this.GetProtocoloAutorizacaoAsync(cnpj, chave, null);
        }
        
        /// <remarks/>
        public void GetProtocoloAutorizacaoAsync(string cnpj, string chave, object userState) {
            if ((this.GetProtocoloAutorizacaoOperationCompleted == null)) {
                this.GetProtocoloAutorizacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProtocoloAutorizacaoOperationCompleted);
            }
            this.InvokeAsync("GetProtocoloAutorizacao", new object[] {
                        cnpj,
                        chave}, this.GetProtocoloAutorizacaoOperationCompleted, userState);
        }
        
        private void OnGetProtocoloAutorizacaoOperationCompleted(object arg) {
            if ((this.GetProtocoloAutorizacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProtocoloAutorizacaoCompleted(this, new GetProtocoloAutorizacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webenefix.com.br/NFCeService/GetPrototoloCancelamento", RequestNamespace="http://webenefix.com.br/", ResponseNamespace="http://webenefix.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetPrototoloCancelamento([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cnpj, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string chave) {
            object[] results = this.Invoke("GetPrototoloCancelamento", new object[] {
                        cnpj,
                        chave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPrototoloCancelamentoAsync(string cnpj, string chave) {
            this.GetPrototoloCancelamentoAsync(cnpj, chave, null);
        }
        
        /// <remarks/>
        public void GetPrototoloCancelamentoAsync(string cnpj, string chave, object userState) {
            if ((this.GetPrototoloCancelamentoOperationCompleted == null)) {
                this.GetPrototoloCancelamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrototoloCancelamentoOperationCompleted);
            }
            this.InvokeAsync("GetPrototoloCancelamento", new object[] {
                        cnpj,
                        chave}, this.GetPrototoloCancelamentoOperationCompleted, userState);
        }
        
        private void OnGetPrototoloCancelamentoOperationCompleted(object arg) {
            if ((this.GetPrototoloCancelamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrototoloCancelamentoCompleted(this, new GetPrototoloCancelamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NFeI")]
    public partial class retStatus {
        
        private string chaveField;
        
        private string detalheAutorizacaoField;
        
        private string detalheCancelamentoField;
        
        private bool emContingenciaField;
        
        private bool emContingenciaFieldSpecified;
        
        private int numeroField;
        
        private bool numeroFieldSpecified;
        
        private string numeroProtocoloAutorizacaoField;
        
        private int oidField;
        
        private bool oidFieldSpecified;
        
        private string statusAutorizacaoField;
        
        private string statusCancelamentoField;
        
        private string urlQrCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string chave {
            get {
                return this.chaveField;
            }
            set {
                this.chaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string detalheAutorizacao {
            get {
                return this.detalheAutorizacaoField;
            }
            set {
                this.detalheAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string detalheCancelamento {
            get {
                return this.detalheCancelamentoField;
            }
            set {
                this.detalheCancelamentoField = value;
            }
        }
        
        /// <remarks/>
        public bool emContingencia {
            get {
                return this.emContingenciaField;
            }
            set {
                this.emContingenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emContingenciaSpecified {
            get {
                return this.emContingenciaFieldSpecified;
            }
            set {
                this.emContingenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified {
            get {
                return this.numeroFieldSpecified;
            }
            set {
                this.numeroFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numeroProtocoloAutorizacao {
            get {
                return this.numeroProtocoloAutorizacaoField;
            }
            set {
                this.numeroProtocoloAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        public int oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oidSpecified {
            get {
                return this.oidFieldSpecified;
            }
            set {
                this.oidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string statusAutorizacao {
            get {
                return this.statusAutorizacaoField;
            }
            set {
                this.statusAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string statusCancelamento {
            get {
                return this.statusCancelamentoField;
            }
            set {
                this.statusCancelamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string urlQrCode {
            get {
                return this.urlQrCodeField;
            }
            set {
                this.urlQrCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void PingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AutorizaCompletedEventHandler(object sender, AutorizaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutorizaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutorizaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public retStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((retStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CancelaCompletedEventHandler(object sender, CancelaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public retStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((retStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void InutilizaCompletedEventHandler(object sender, InutilizaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InutilizaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InutilizaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string detalhes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetStatusPorChaveCompletedEventHandler(object sender, GetStatusPorChaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusPorChaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusPorChaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public retStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((retStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetStatusPorOidCompletedEventHandler(object sender, GetStatusPorOidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusPorOidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatusPorOidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public retStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((retStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetDocCompletedEventHandler(object sender, GetDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUrlConsultaCompletedEventHandler(object sender, GetUrlConsultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUrlConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUrlConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUrlQrCodeCompletedEventHandler(object sender, GetUrlQrCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUrlQrCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUrlQrCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetQrCodeCompletedEventHandler(object sender, GetQrCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetQrCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQrCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetProtocoloAutorizacaoCompletedEventHandler(object sender, GetProtocoloAutorizacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProtocoloAutorizacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProtocoloAutorizacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetPrototoloCancelamentoCompletedEventHandler(object sender, GetPrototoloCancelamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrototoloCancelamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrototoloCancelamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591