//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSoftware.Modulos.IMEXApp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class UrlIMEXApp : global::System.Configuration.ApplicationSettingsBase {
        
        private static UrlIMEXApp defaultInstance = ((UrlIMEXApp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UrlIMEXApp())));
        
        public static UrlIMEXApp Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApiCategoriaProduto/Post")]
        public string PostCategroriaProduto {
            get {
                return ((string)(this["PostCategroriaProduto"]));
            }
            set {
                this["PostCategroriaProduto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApiCategoriaProduto/GetRegistros/")]
        public string GetRegistrosCategoriaProduto {
            get {
                return ((string)(this["GetRegistrosCategoriaProduto"]));
            }
            set {
                this["GetRegistrosCategoriaProduto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApiCategoriaProduto/Delete/")]
        public string DeleteRegistrosCategoriaProduto {
            get {
                return ((string)(this["DeleteRegistrosCategoriaProduto"]));
            }
            set {
                this["DeleteRegistrosCategoriaProduto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApIunidademedida/Post")]
        public string PostUnidaDeMedida {
            get {
                return ((string)(this["PostUnidaDeMedida"]));
            }
            set {
                this["PostUnidaDeMedida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApIunidademedida/GetRegistros/")]
        public string GetRegistrosUnidadeMedida {
            get {
                return ((string)(this["GetRegistrosUnidadeMedida"]));
            }
            set {
                this["GetRegistrosUnidadeMedida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApIunidademedida/Delete/")]
        public string DeleteRegistrosUnidadedeMedida {
            get {
                return ((string)(this["DeleteRegistrosUnidadedeMedida"]));
            }
            set {
                this["DeleteRegistrosUnidadedeMedida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApiTransportadora/Post")]
        public string PostTransportadora {
            get {
                return ((string)(this["PostTransportadora"]));
            }
            set {
                this["PostTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApiTransportadora/Delete/")]
        public string DeleteRegistrosTransportadora {
            get {
                return ((string)(this["DeleteRegistrosTransportadora"]));
            }
            set {
                this["DeleteRegistrosTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApiTransportadora/GetRegistros/")]
        public string GetRegistrosTransportadora {
            get {
                return ((string)(this["GetRegistrosTransportadora"]));
            }
            set {
                this["GetRegistrosTransportadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApiPrazo/Post")]
        public string PostPrazo {
            get {
                return ((string)(this["PostPrazo"]));
            }
            set {
                this["PostPrazo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApiPrazo/Delete/")]
        public string DeleteRegistrosPrazo {
            get {
                return ((string)(this["DeleteRegistrosPrazo"]));
            }
            set {
                this["DeleteRegistrosPrazo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://hlpsistemas.sytes.net:8085/api/ApiPrazo/GetRegistros/")]
        public string GetRegistrosPrazo {
            get {
                return ((string)(this["GetRegistrosPrazo"]));
            }
            set {
                this["GetRegistrosPrazo"] = value;
            }
        }
    }
}
